### ISSUE TITLE
Burn should ensure upgrade related bundles are always planned to execute last to maintain inter-bundle dependencies.

### ISSUE THREAD

**Issue by QaiserSadiq** [wixtoolset/issues#5128]
User stories
• As a Setup developer I can implement related bundles and be ensured that my “Addon” and “Patch” burn bundles will execute first in order to maintain inter-bundle dependencies.  

Proposal
Currently the order of how the related bundles are executed is non-deterministic and based on bundle GUID order which can vary based on the system.  In certain cases, this can lead to bundles being executed before others solely based on their GUIDs.
This proposal suggests that instead of relying only on the bundle GUID, we should take the relationship type (Upgrade and non-Upgrade) into account when determining the order of execution of the related bundle.  The following is the suggested order:
1.  All non-Upgrade related bundle relationship types should be handled first to prevent them from being incorrectly removed before they have had a chance to register during the uninstallation of the older bundle (this occurs for some Addon and Patch related bundles).
2.  Upgrade.

To clarify, within each type the order of execution will remain what we currently have implemented today.  This proposal creates two ordered groups/classes all non-Upgrade related bundles and Upgrade bundles.

The fix is currently being tested. 

Considerations
While this new functionality would solve the issue for ordering when setup actions get performed on non-Upgrade/Upgrade “types” of related bundles, it does not provide additional granularity (GUID by GUID within a type) should the Setup developer require it.

**Comment by barnson** [comment]
We should order all relation types instead of just upgrade/non-upgrade. We'd consider this for v3.x depending on complexity. Also, please expand on the problem being solved -- what doesn't work with the current random order.

**Comment by heaths** [comment]
We considered ordering other types as well, but since the enum isn't a flags-style enum the code change churn required was more than the need to do so.

The main problem is called out in the WIP (not yet committed; I'll work with @QaiserSadiq to do so), that if the order is random (whatever RegEnumKey returns, which varies from machine to machine) a few things can happen:

1. During install, an upgrade bundle may run before a patch bundle, which fails the patch bundle.
2. During install, an upgrade bundle that runs first may cause the ugpradee to be removed, thus removing any addons (like an LP) that was not yet ref-counted by the upgrader, so it gets removed instead of left behind if the upgrade bundle first found and re-installed / recognized the addon related bundle.

**Comment by BDSuther** [comment]
I've run into this same issue after deciding to use the existing Addon related bundle functionality in WiX. Previously I had detected all the addons and overridden the default Plan to ensure addons were uninstalled when uninstalling the parent product. By using an Addon related bundle this was handled automatically by WiX. Spent a few days updating our installer projects so that the Addon bundles are now defining that they are an Addon to the main product bundle. During QA testing sometimes Addons are removed with an upgrade, sometimes they are not.

Here's an example of the Burn bundle's log on an upgrade (ommitting some things). Note that it detected the old bundle to upgrade before the Addon bundle.

> [02C4:0AC0][2018-07-23T12:36:46]i102: Detected related bundle: {46e9bb40-522b-420c-b826-d9032cc0f5f7}, type: Upgrade, scope: PerMachine, version: 7.1.0.26215, operation: MajorUpgrade
> [02C4:0AC0][2018-07-23T12:36:46]i102: Detected related bundle: {9117471a-5105-460e-b0f6-6a96fb8c1ba7}, type: Addon, scope: PerMachine, version: 1.1.0.26150, operation: Install
> ...
> [02C4:0AC0][2018-07-23T12:36:52]i200: Plan begin, 18 packages, action: Install
> ...
> [02C4:0AC0][2018-07-23T12:36:52]i207: Planned related bundle: {46e9bb40-522b-420c-b826-d9032cc0f5f7}, type: Upgrade, default requested: Absent, ba requested: Absent, execute: Uninstall, rollback: Install, dependency: None
> [02C4:0AC0][2018-07-23T12:36:52]i207: Planned related bundle: {9117471a-5105-460e-b0f6-6a96fb8c1ba7}, type: Addon, default requested: Present, ba requested: Present, execute: Install, rollback: None, dependency: Register
> ...
> [0A4C:0744][2018-07-23T12:45:38]i301: Applying execute package: {46e9bb40-522b-420c-b826-d9032cc0f5f7}, action: Uninstall, path: C:\ProgramData\Package Cache\{46e9bb40-522b-420c-b826-d9032cc0f5f7}\7.1.0.0 Installer.exe, arguments: '"C:\ProgramData\Package Cache\{46e9bb40-522b-420c-b826-d9032cc0f5f7}\7.1.0.0 Installer.exe" -uninstall -quiet -burn.related.upgrade -burn.ancestors={30c7e341-5fec-4287-9d79-1bc99f9fe4ef} -burn.filehandle.self=448'
> [02C4:0AC0][2018-07-23T12:45:57]i319: Applied execute package: {46e9bb40-522b-420c-b826-d9032cc0f5f7}, result: 0x0, restart: None
> [0A4C:0744][2018-07-23T12:45:57]i301: Applying execute package: {9117471a-5105-460e-b0f6-6a96fb8c1ba7}, action: Install, path: C:\ProgramData\Package Cache\{9117471a-5105-460e-b0f6-6a96fb8c1ba7}\1.1.0.0 Installer.exe, arguments: '"C:\ProgramData\Package Cache\{9117471a-5105-460e-b0f6-6a96fb8c1ba7}\1.1.0.0 Installer.exe" -quiet -burn.related.addon -burn.ignoredependencies={30c7e341-5fec-4287-9d79-1bc99f9fe4ef} -burn.ancestors={30c7e341-5fec-4287-9d79-1bc99f9fe4ef}'
> [0A4C:0744][2018-07-23T12:45:57]e000: Error 0x80070003: Failed to create embedded process at path: C:\ProgramData\Package Cache\{9117471a-5105-460e-b0f6-6a96fb8c1ba7}\1.1.0.0 Installer.exe
> [0A4C:0744][2018-07-23T12:45:57]e000: Error 0x80070003: Failed to run bundle as embedded from path: C:\ProgramData\Package Cache\{9117471a-5105-460e-b0f6-6a96fb8c1ba7}\1.1.0.0 Installer.exe
> [0A4C:0744][2018-07-23T12:45:57]e000: Error 0x80070003: Failed to execute EXE package.
> [02C4:0AC0][2018-07-23T12:45:57]e000: Error 0x80070003: Failed to configure per-machine EXE package.
> [02C4:0AC0][2018-07-23T12:45:57]w350: Applied non-vital package: {9117471a-5105-460e-b0f6-6a96fb8c1ba7}, encountered error: 0x80070003. Continuing...
> [0A4C:0744][2018-07-23T12:45:57]i325: Registering dependency: {30c7e341-5fec-4287-9d79-1bc99f9fe4ef} on package provider: {9117471a-5105-460e-b0f6-6a96fb8c1ba7}, package: {9117471a-5105-460e-b0f6-6a96fb8c1ba7}

During the Uninstall of the previous version, it detects and plans to uninstall the Addon package since there is no dependent still registered at that time. Once the previous version is done installing, the Upgrading bundle tries to register the dependency with the Addon making an empty Registry entry in HKLM\SOFTWARE\Calsses\Installer for the Addon installer's GUID. Additionally you'll notice that we get several HRESULT PATH_NOT_FOUND (8007003) errors.

In the opposite order the behaviour is as expected. The dependency is registered on the Addon bundle and when we remove the previous bundle it does not plan to remove the Addon since 1 dependent is detected.

This issue basically makes Addon bundles un-usable in production since it will randomly uninstall Addons during the main product upgrades
