### ISSUE TITLE
WIP template links to old site repo

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#5174]
wixtoolset.org/development/wips/0000-wix-improvement-proposal/ points to the deleted wixtoolset/site repo instead of the new wixtoolset/web repo.

(pull request coming, this is mostly for trying out the new flow)

**Comment by rseanhall** [comment]
I can't figure out how to actually assign this to myself, perhaps I don't have the rights.

**Comment by robmen** [comment]
The lack of assignment flexibility is one of the huge downsides of GitHub issues over [tinybugs](http://github.com/robmen/tinybugs). I think we'll just have to look in the comments for people declaring their intent. Of course, a pull request with a fix for the bug is a great way to lick the cookie as well.
