### ISSUE TITLE
Directory search in registry

### ISSUE THREAD

**Issue by EMostafaAli** [wixtoolset/issues#5271]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.10.2.2516

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2015 V 14.0.25123.00 Update 2

* Which version of .NET are you building with?

> 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10

* Describe the problem and the steps to reproduce it.

> I have a registry entry "C:\Program Files\Computers and Structures\SAP2000 18\" and I am writing the following property to get the directory.

```
<Property Id="SAP2000INSTALLATIONV18_64">
      <RegistrySearch Id="SAP2000Registryv18_64" Root="HKLM" Key="Software\Computers and Structures, Inc.\SAP2000\18" Name="Install path" Type="directory" Win64="yes">
        <DirectorySearch Id="SAP2000Pathv18_64" Path="[SAP2000INSTALLATIONV18_64]"/>
      </RegistrySearch>
    </Property>
    <Condition Message="Path does not exist">
      <![CDATA[SAP2000INSTALLATIONV18_64]]>
    </Condition>
```

> I found the installer can't run unless I change the type to "raw" instead of "directory". For me, it seems a legitimate path.

> Please note the same code works for the same path if it is 32 bit.

**Comment by barnson** [comment]
Works for me:

    <Property Id="FOO">
        <RegistrySearch Root="HKLM" Key="HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework" Name="InstallRoot" Win64="yes" Type="directory" Id="NetFrameworkInstallRootSearch">
            <DirectorySearch Id="NetFrameworkInstallRootSearch" />
        </RegistrySearch>
    </Property>

And the searches are a built-in functionality of Windows Installer. WiX can't change their behavior, only replace them.

**Comment by EMostafaAli** [comment]
Actually, It works with me as well for other entries but not this one.

**Comment by barnson** [comment]
MSI owns the AppSearch process so unless you're finding that WiX isn't building the AppSearch tables correctly, there's nothing WiX can do to change AppSearch behavior.

**Comment by TannerStevenson** [comment]
I believe I may also be having the same issue, but I am not entirely convinced that this is an external issue. To me it seems that the DirectorySearch and FileSearch elements are not behaving as they should be. Here is what I found: 

I first do a registry search to find the directory in which I want to perform the file search:
```
<Property Id="ACQHOME">
      <RegistrySearch Id='AcqHomeRegistrySearch' Type='raw'
                      Root='HKLM' Key='Path\To\Key'
                      Name='Home' Win64='no'/>
</Property>
```

This loads the path just fine. Then I search for my file in the following way:
```
<Property Id="FILEEXISTS">
      <DirectorySearch Id="DirSearch" Path="[ACQHOME]">
            <FileSearch Name="LibraryName.dll"/>
      </DirectorySearch>
</Property>
```

But this doesn't work. It never finds the file even if it exists:

> AppSearch: Property: FILEEXISTS, Signature: DirSearch
MSI (c) (60:28) [22:32:04:344]: Note: 1: 1325 2: LibraryName.dll 

I thought it might be caused by the [ACQHOME] variable not being available or populated. So I tried the following:
```
<Property Id="FILEEXISTS">
      <DirectorySearch Id="DirSearch" Path="[ACQHOME]" AssignToProperty="yes"/>
</Property>
```

Well, the property is available and can resolve correctly!

> AppSearch: Property: FILEEXISTS, Signature: DirSearch
MSI (c) (60:28) [22:32:04:346]: PROPERTY CHANGE: Adding FILEEXISTS property. Its value is 'Path\To\Directory'.

Then I tried nesting the directory search within a RegistrySearch so I shouldn't have to worry about the path getting resolved:
```
<Property Id="FILEEXISTS">
      <RegistrySearch Id='RegistrySearch'
                      Type='directory' Root='HKLM'
                      Key='Path/To/Key'
                      Name='Home' Win64='no'>
              <DirectorySearch Id="RegistrySearch" >
                    <FileSearch Name="FileName.dll"/>
             </DirectorySearch>
      </RegistrySearch>
</Property>
```

But this causes the installer to crash outright in a seemingly infinite loop:

> AppSearch: Property: FILEEXISTS, Signature: RegistrySearch
MSI (c) (60:28) [22:32:04:350]: Note: 1: 1325 2: FileName.dll 
MSI (c) (60:28) [22:32:04:353]: Note: 1: 1322 2:  
MSI (c) (60:28) [22:32:04:353]: Note: 1: 1322 2:  
MSI (c) (60:28) [22:32:04:353]: Note: 1: 1325 2: FileName.dll 
MSI (c) (60:28) [22:32:04:354]: Note: 1: 1322 2:  
MSI (c) (60:28) [22:32:04:354]: Note: 1: 1322 2:  
MSI (c) (60:28) [22:32:04:354]: Note: 1: 1325 2: FileName.dll ... until it crashes

Out of options, I tried hardcoding the path in the DirectorySearch just to know what the correct functionality is supposed to look like:
```
<Property Id="FILEEXISTS">
      <DirectorySearch Id="DirSearch" Path="Path\To\File">
             <FileSearch Name="LibraryName.dll"/>
      </DirectorySearch>
</Property>
```

And sure enough that works:
> AppSearch: Property: FILEEXISTS, Signature: DirSearch
MSI (c) (60:28) [22:32:04:349]: Note: 1: 1325 2: LibraryName.dll 
MSI (c) (60:28) [22:32:04:349]: PROPERTY CHANGE: Adding FILEEXISTS property. Its value is 'Path\To\File'.

So I am sufficiently stumped and frustrated. For now I will just use a custom method, but it would be nice to find a better way, if there is one.

I am using Wix 3.11.0 with Visual Studio 2015 on Windows 10.
