### ISSUE TITLE
Splash screen appears too late

### ISSUE THREAD

**Issue by cmlr72** [wixtoolset/issues#5300]
Wix 3.10.2.2516, installing on Windows 7 SP1 (shouldn't matter though)

When installing a bundle with lots of payloads (several 1000s), the splash screen appears far too late. 

Engine initialization takes several seconds (>10), then the splash screen blinks up shortly just before the user interface is shown.

Reason: 

ManifestLoadXmlFromBuffer takes a lot of time with a large number of payloads. Almost exclusively because of PayloadFindById btw, maybe this could be optimized somehow as well.
So, EngineRun with engineState.mode==BURN_MODE_UNTRUSTED doesn't show a splash screen at all, calls ManifestLoadXmlFromBuffer, then starts another bootstrapper instance in BURN_MODE_NORMAL, which calls ManifestLoadXmlFromBuffer again and eventually calls RunNormal and SplashScreenCreate after that. Therefore the whole time consuming init phase isn't covered by the splash screen, making it largely useless.

SplashScreenCreate should be called at least before loading packages and payloads from the manifest, and already in BURN_MODE_UNTRUSTED. It could be closed when the second instance is launched, and reopened by the second instance, which causes a short blink of the splash screen, but that would be acceptable (VS installer seems to do the same).

**Comment by MikeF74** [comment]
I am having a big problem with this myself.  In v3.11, my splash screen will not show until 45 seconds after launching my large installer because it unpacks the 700MB or so in payloads before it shows the splash screen.  Then, it shows the splash screen 2 seconds before my managed WPF UI is shown.  It really seems like the splash should be displayed before the payloads are unpacked.  Is there anyway way to indicate to the user that something is happening?

**Comment by barnson** [comment]
Burn only unpacks the BA payloads up-front; everything else is unpacked as needed. The bug is open for someone to optimize for splash screen loading.
