### ISSUE TITLE
wix uninstall not removing installed folder

### ISSUE THREAD

**Issue by shritis** [wixtoolset/issues#5449]
Hi, 
We are having majorupgrade from v8 to v9. Have created the setup successfully. The setup also works fine.

The problem is, on uninstall. While uninstalling the program it doesnt remove the installed folder. Our v8 setup will install V8 folder in APPDATA/SpreadsheetConverter/V8 and v9 setup will install V9 folder in the same path, like APPDATA/SpreadsheetConverter/V9. While uninstalling when there is only V9 is installed then the folder removes properly, but when there is V8 folder present, then the folder is not removed. I have checked that creating new GUID for component solves the problem. but its so hard to change each component guid as there are lots of files.

What should i do?

**Comment by rseanhall** [comment]
Please ask your question on the [wix-users mailing list](http://wixtoolset.org/documentation/mailinglist/).

The WiX Toolset has been around for a long time, so we use this issue tracker differently than most other projects. For questions like this, you are going to get much better answers faster on the [wix-users mailing list](http://wixtoolset.org/documentation/mailinglist/) because that's where people have been asking questions since 2004. While discussing your question, we may discover a specific bug or feature to be tracked here but usually someone can help solve your issue.

**Comment by shritis** [comment]
hi, how can i mail to wix-users mailing list

**Comment by rseanhall** [comment]
http://lists.wixtoolset.org/listinfo.cgi/wix-users-wixtoolset.org
