### ISSUE TITLE
Burn installer launched by standard user cannot perform system restart even elevated at Apply

### ISSUE THREAD

**Issue by octomata** [wixtoolset/issues#5499]
* Which version of WiX are you building with?

3.10.3.3007

* Which version of Visual Studio are you building with (if any)?

Visual Studio 2013

* Which version of .NET are you building with?

.NET 4.5.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows Server 2008 R2, Windows Server 2012 R2, Windows Server 2016

* Describe the problem and the steps to reproduce it.

The burn bundle installer was created with a MBA and one exe package in the chain. If the exe package returns exitcode 3010, the bootstrapper application will return IDRESTART at OnShutdown().

If the machine is run using administrator account, the machine can be restarted.
If the machine is run on Windows workstation OS (e.g. windows 7) using standard user with UAC elevated at Apply, the machine can be restarted.
But if the machine is run on Windows server OS (e.g. windows 2012 R2) using standard user with UAC elevated at Apply, the machine cannot be restarted.

By default standard users has shutdown privilege available on windows workstation OS but not windows server OS.
But if the user has been granted shutdown user right through group policy, restart can be performed.

* Describe the behavior you expected and how it differed from the actual behavior.

As the installer has been elevated, it is expected that the wix engine should be able to restart the machine if OnShutdown() returns IDRESTART.

The log is saying "Restarting Computer..." but the system does not restart.
And DebugView is showing
`[2988] TraceError 0x80070005: Root failure at engine.cpp:886 `

**Comment by vanni-giachin** [comment]
@barnson I am facing the same exact behaviour for administrator users on Windows Server 2019 only. I don't know if the error is the same on debug because I didn't try.
The reboot is triggered by the `<ExitCode ... Behavior="forceReboot"/>` statement on package (.Net Framework setup).
The burn is built by using the v3.11.2 binaries.
The workarounds are to run the burn installer _As Adminsitrator_ or to reboot the machine manually. 
The burn logs have `WixBundleElevated = 1` then `Exit code: 0x669, restarting: Yes` and `Restarting computer...`.

**Comment by vanni-giachin** [comment]
I opened a separate case since I found additional info, and the problem looks different: #6145

**Comment by armsee** [comment]
Now since Windows Server 2019 has become more and more widespread, this issue is becoming an ever greater problem for our customers and therefore also for us.
