### ISSUE TITLE
Unable to create an internet shortcut with util:InternetShortcut

### ISSUE THREAD

**Issue by jcasale** [wixtoolset/issues#5522]
The behavior of util:InternetShortcut has changed in wix 3.11.1507.0 with vs2017 extensions 0.9.10.21458 where if IconFile is not present, then the projects errors indicating ```Cannot set column 'IconFile' with a null value because this is a required field.``` and if you include and set the attribute to an empty string then a different error is returned ```The util:InternetShortcut/@IconFile attribute's value cannot be an empty string. If a value is not required, simply remove the entire attribute.```

The following two mailing list threads cover it as well:

- [\[wix-users\] InternetShortcut broken in WiX 3.11 ?](http://lists.wixtoolset.org/pipermail/wix-users-wixtoolset.org/2017-March/004472.html)
- [\[wix-users\] Unable to create internet shortcut](http://lists.wixtoolset.org/pipermail/wix-users-wixtoolset.org/2017-March/004475.html)

**Comment by danlyons-softek** [comment]
I started looking into using wix 3.11 RC because I'm wanting to switch over to Visual Studio 2017.  However, in doing so, I ran into the same problem.  All the InternetShortcut elements in my installer projects now fail the build with `candle.exe : error CNDL0001: Cannot set column 'IconFile' with a null value because this is a required field`

This seems related to the changes for #3163

Judging by the changes for the related pull request and the surrounding code, it seems like [UtilDecompiler.cs, line 536](https://github.com/wixtoolset/wix3/blob/be0abc821d662c0a9e8bc122ee662392f87eb847/src/ext/UtilExtension/wixext/UtilDecompiler.cs#L536) needs to be wrapped in an `if(null != (string)row[6])` block.

**Comment by danlyons-softek** [comment]
To work around this issue, I decided to go ahead and add IconFile references to my InternetShortcut elements.  However, it does not work even if I _do_ supply IconFile.  Rather than failing to build, it now fails to install.

If I include IconFile referencing an icon file without an index, like the following:
```
<util:InternetShortcut
    Id="shortcut_rabbitmq_management"
    Name="!(loc.Shortcut_RabbitMQ_Management)"
    Target="http://localhost:15672/"
    IconFile="c:\users\administrator\desktop\favicon.ico" />
```
or even an executable like the following:
```
<util:InternetShortcut
    Id="shortcut_rabbitmq_management"
    Name="!(loc.Shortcut_RabbitMQ_Management)"
    Target="http://localhost:15672/"
    IconFile="[System32Folder]credwiz.exe" />
```

I get the following error:
```
WixCreateInternetShortcuts:  Error 0x80070103: failed to read shortcut icon path from custom action data
CustomAction WixCreateInternetShortcuts returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
```

If I include IconFile referencing a shell DLL file and providing an IconIndex, like the following:
```
<util:InternetShortcut
    Id="shortcut_rabbitmq_management"
    Name="!(loc.Shortcut_RabbitMQ_Management)"
    Target="http://localhost:15672/"
    IconFile="[System32Folder]SHELL32.dll"
    IconIndex="152"/>
```

I get the following error:
```
WixCreateInternetShortcuts:  Creating IShellLinkW shortcut 'C:\Users\Public\Desktop\Errors.lnk' target 'https://localhost/panther/admin/usererror.aspx'
WixCreateInternetShortcuts:  Error 0x80070103: failed to read shortcut icon index from custom action data
CustomAction WixCreateInternetShortcuts returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
```

Note that in all the above cases, I can manually create a .url file with the properties that works, either through the properties dialog or by modifying IconFile (and optionally IconIndex) directly with notepad, though the latter usually requires I relog on my test VM.

**Comment by robertmuehsig** [comment]
I have the same issue and this seems currently the main blocker to change to VS2017. Is there any "working" workaround available?

**Comment by jcasale** [comment]
@robertmuehsig Sure, use a regular shortcut:

```xml
    <Property Id="Url" Value="http://example.com" />
    <Icon Id="MyIcon" SourceFile="...\MyApp.exe" />
    <Shortcut Id="SomeId"
                  Name="Some Shortcut"
                  Description="Some Description"
                  Icon="MyIcon"
                  Target="[Url]" />
```
