### ISSUE TITLE
Install VSIX package both in Visual Studio 2015 and Visual Studio 2017

### ISSUE THREAD

**Issue by hugoqribeiro** [wixtoolset/issues#5566]
* Which version of WiX are you building with?

> 3.11.0.1528

* Which version of Visual Studio are you building with (if any)?

> VS2017 Version 15.1 (26403.7)

* Which version of .NET are you building with?

> .NET 4.6.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10

* Describe the problem and the steps to reproduce it.

I have a wix setup project that installs a set of VSIX packages. It has been working correctly with VS2015 using the wix:VsixPackage element from the VS extension.

I've updated the project to try to install the VSIX packages both in VS2015 and VS2017 like this:

```
<Component Id="Modeling.Factory" Guid="1A5C7D5C-676E-46D9-9808-5FE79A51B8B3">
    <File
        Id="Modeling.Factory.vsix"
        Name="Primavera.Modeling.Factory.Shell3.vsix"
        Source="$(var.SolutionDir)\Bin\Primavera.Modeling.Factory.Shell3.vsix"
        Vital="yes">
        <wix:VsixPackage
            PackageId="FA9F2DC1-30A2-4C88-AFC6-3CD5A49C39CB"
            Target="Pro"
            TargetVersion="14.0"
            Permanent="no"
            Vital="yes" />
        <wix:VsixPackage
            PackageId="FA9F2DC1-30A2-4C88-AFC6-3CD5A49C39CB"
            Target="Pro"
            TargetVersion="15.0"
            Permanent="no"
            Vital="yes" />
    </File>
</Component>
```

The project builds but the setup fails with the following error (extracted from the msi log file):

```
MSI (s) (74:1C) [11:20:39:315]: Executing op: CustomActionSchedule(Action=vim2916624A52A9C02C06B731DECBEAB911,ActionType=3122,Source=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe,Target=/q  /skuName:Pro /skuVersion:15.0 "C:\Program Files (x86)\PRIMAVERA\Elevation SDK v3.00\Temp\Primavera.Modeling.Factory.Shell3.vsix" /admin,)
CustomAction vim2916624A52A9C02C06B731DECBEAB911 returned actual error code 2003 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (s) (74:1C) [11:20:39:774]: Note: 1: 1722 2: vim2916624A52A9C02C06B731DECBEAB911 3: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe 4: /q  /skuName:Pro /skuVersion:15.0 "C:\Program Files (x86)\PRIMAVERA\Elevation SDK v3.00\Temp\Primavera.Modeling.Factory.Shell3.vsix" /admin 
```

So the issue here is that wix is trying to install the VSIX package with the VS2015 VSIXInstaller.exe.

Here's the complete log file:

[log.txt](https://github.com/wixtoolset/issues/files/946794/log.txt)

* Describe the behavior you expected and how it differed from the actual behavior.

The expected behavior is that the VSIX package is installed correctly on VS2015 and VS2017.
I suppose that v3.11 cannot be released without fully supporting VSIX packages.

**Comment by barnson** [comment]
VsixPackage doesn't support VS2017. https://github.com/wixtoolset/issues/issues/5433

**Comment by hugoqribeiro** [comment]
The question is: will it ever support it? I can't get that information clearly from the issue you mentioned?

**Comment by robmen** [comment]
Unfortunately, not clear. VS has a design issue they need to resolve.

**Comment by niemyjski** [comment]
Is this supported now?

**Comment by robmen** [comment]
No. There is a still design issue in `VSIXInstaller.exe` that prevents this from working fully in VS2017. There was a discussion very recently about it on wix-devs mailing list.

**Comment by niemyjski** [comment]
So what's the work around? I need to support VS2017

**Comment by barnson** [comment]
VsixPackage doesn't support VS2017. #5433

**Comment by niemyjski** [comment]
That issue is closed for no specific reason,

Thanks
-Blake Niemyjski

**Comment by robmen** [comment]
@heaths was doing work on the feature then hit roadblocks that required `VsixInstaller.exe` improvements. So, back in March (or so) Heath finished the detection work (which was possible and now works). The `VsixInstaller.exe` now needs to address the issues Heat discovered before there is anything we can do in the WiX Toolset to install VSIXs via an MSI package.

So, you need to lean on the VS team at this point. When VS commit to fixing `VsixInstaller.exe` then someone here could finish the work that Heath started. Until then, there isn't much we can do with VsixPackage for VS2017.

Again, IIRC, there was a thread on wix-devs recently where Heath reiterated the gory details.

**Comment by hugoqribeiro** [comment]
Any link to track the vsinstaller.exe issue(s) that you mention?

**Comment by robmen** [comment]
http://lists.wixtoolset.org/pipermail/wix-devs-wixtoolset.org/

**Comment by heaths** [comment]
Publicly, no. Depending on to what changes @robmen is referring, _VSIXInstaller_ has made changes I requested of them in 15.2 to treat 14- and 15+ as separate so we can write a custom action that can target either/or (as mentioned in my WIP).

However, that _VSIXInstaller_ might install MSIs even when launched from MSI is not something we are currently planning to address. If any extensions take dependencies on other workloads besides CoreEditor (pretty rare for extensions currently), there is the https://github.com/Microsoft/vsixbootstrapper workaround.

I just have not had time to go back and make all the changes necessary. I don't know when I might, but happy to serve an advisory role to help someone else implement it (much is in the WIP, but various nuances are stuck in my head). There's also a lot of examples in the various OSS projects with which I've been busy like the one mentioned above, https://github.com/Microsoft/vswhere and https://github.com/Microsoft/vssetup.powershell from which people can draw.

**Comment by niemyjski** [comment]
I'd be more than happy to contact the vs team and prod them if there was a
public discussion of issues (which should be on GitHub and not in some
mailing list............). My extension only takes core editor. I thought
this stuff was address in the currently release. So what is the
recommendation just provide the installer and vsix or shell the vsix after
the installer is done?

Thanks
-Blake Niemyjski

**Comment by robmen** [comment]
Sounds like the first set issues blocking the VsixPackage from working correctly were addressed. If your VSIX only depends on CoreEditor then VsixPackage could succeed. Now someone just needs to finish the work that @heaths started. He offered to help out in an advisory role.

At this point, the discussion should take place on wix-devs mailing list.

**Comment by niemyjski** [comment]
Rob can you respond to the mailing list thread.. I just joined and have no
clue where it is or how to reply to it..

Thanks
-Blake Niemyjski

**Comment by barnson** [comment]
@heaths Previously, you hinted that VSIXInstaller might be updated to fail if an extension requested a not-yet-installed workload/component. Is that to say it will fail early or fail because of an attempt at a concurrent MSI installation?

**Comment by heaths** [comment]
@barnson I'll reply right now with my plan in the current email thread on feature 5433. @niemyjski I don't see any email from you. You have to be subscribed before you can send to either wix-devs or wix-users, and this conversation is on wix-devs (about development of WiX).

**Comment by niemyjski** [comment]
I've subscribed and got conformation emails and also received a few from
wix users. I've also sent multiple emails with no reply back

Thanks
-Blake Niemyjski

**Comment by heaths** [comment]
@niemyjski you need to subscribe to wix-devs. There is currently no support for installing VS2017 extensions in MSI via WiX, which is why we're discussing it on the developer alias. Or, use the existing properties (I already updated the WixVSExtension for 3.11 and some build of 4.x) to support finding VSIXInstaller, so you can duplicate the authoring (see the VSExtension source here on GitHub) and run it yourself, though without the work we're discussing it will install into all instances so if you only depend on CoreEditor that should be fine). In fact, with the changes I made, just using the `VsixPackage` would a CoreEditor-only package should already just work.

**Comment by niemyjski** [comment]
@heaths I've subscribed but haven't gotten anything back from my subscription emails other than a hello email. I've sent emails and received nothing in return.. It's kind of frustrating on both sides of the fence..

I truly think mailing lists are not a place for conversation on a public project of this size. GitHub issues even if they are questions are very useful to look at and search through via google.... 

What specific issues from VS are we currently blocked on? I'd be more than happy to reach out to those teams and get the ball rolling.  Currently from all the pain and suffering I've pretty much murdered our wix implementation for (https://codesmithtools.com) and we'll be shipping a vsix sxs and we've also removed everything but very basic components from wix. Perhaps in the near future we will just be xcopy deployed. I've talked with a few others who have also done the same.

**Comment by robmen** [comment]
GitHub issues are *horrible* to track if you're trying to manage a project because there's no "read" status. It's impossible to track threads (within GitHub) that as a maintainer I have to comeback and respond to later (because I can't respond to all issues immediately).

Email handles read state trivially. And email is archived. That's why we use email discussion not GitHub.

Anyway, @niemyjski, I saw your email to wix-devs and there have been a few emails since you joined. I don't know why you are not getting email. Email is usually trivial 

Finally, I agree that VS is pushing all Visual Studio integrators into VSIX. We pushed all of our WiX Toolset VS integration out to a VSIX for this reason. We basically just quit fighting them. So it doesn't surprise me you're moving your dev tools to VSIX as well. You might do the same as us and give up and just use VISX as the entry point for your tools and MSI for the stuff that you can't/don't want to put in VSIX. Then you don't install your VSIX via your MSI (if anything you do it the other way around and have your VS integration download the MSI).

But it'd still be awesome if someone wanted to finish the installation of VSIX via MSI, and that discussion has been happening wix-devs for last few days.

**Comment by niemyjski** [comment]
I'm not sure either :\, but it's not in my inbox or spam folders (email is unreliable too), which is why I like GitHub because it has both emails (respond to quickly) and notifications that show you things you haven't read or missed. Might be worth signing up with a new email and testing it, because it's not working on my end with gmail.

We've always been in a vsix format but we were tied to the gac and other things like msbuild so we needed it installed via an installer. Also we had a feature flag that let them install it quickly and it was managed in one place which was also nice. I'd say that if the feature isn't complete or won't be completed by the community then the whole feature set should be removed completely (give up). Also, I'm not sure how it could possibly detect the correct registry entries since it's using an isolated registry (https://developercommunity.visualstudio.com/content/problem/2813/cant-find-registry-entries-for-visual-studio-2017.html).

**Comment by robmen** [comment]
@niemyjski I created you a new Gmail account `wix.blake.niemyjski@gmail.com` yesterday and it is sending and receiving emails without issue. Feel free to contact me offline (email or Twitter DM) to get the password. I don't know why your current Gmail account would not be working correctly.

Also, sounds like you have a totally reasonable design. This issue just needs to get completed.

**Comment by heaths** [comment]
The feature work I've laid out in email is using support APIs. I didn't have time to work on it this past week as I had hoped, but if someone else is going to work on implementing those plans (nothing else would be officially supported) I need to know so I don't otherwise start.

Any discussion on the feature itself should continue via email.
