### ISSUE TITLE
WixTasks GenerateCompileWithObjectPath fails with FIPS-compliant error on FIPS-enabled machine

### ISSUE THREAD

**Issue by ljboiler** [wixtoolset/issues#5672]
Request that the MSBuild WixTasks be updated to honor the fipsCompliant setting when running the GenerateCompileWithObjectPath task, to avoid the "InvalidOperationException:  This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms"

**Comment by Herohtar** [comment]
@robmen @barnson Would you be okay with me submitting a fix for this in v3 along with the fix for https://github.com/wixtoolset/issues/issues/4368? I could possibly put together a separate PR for v4 as well if that helps.

**Comment by BMurri** [comment]
Especially if your fix for #4368 fixes this issue as well, yes, that would be great.

The request is to always implement every fix in v4 unless it is not applicable. If possible, use the repos off of Home instead of the old wix4 repo.

In general, we can still take breaking changes in v4, so if something should default, you can do that in v4 (until we publicly release). v3 has a strict bar, so as reiterated it has to be opt-in only, and even then...

**Comment by LYDE1234** [comment]
Could someone please verify that this issue is about executing the WixToolset in a FIPS-compliant setting, i.e. building installables with Wix in a FIPS-compliant environment, for example under the Win FIPS group policy? It has nothing to do with FIPS-compliancy of the output files / the installables themselves. Is this correct?

**Comment by ljboiler** [comment]
I will verify that the issue is about executing the WixToolset in an environment where the FIPS-compliant setting has been enabled.
