### ISSUE TITLE
Wix Firewall exception extension not over writing existing firewall exceptions.

### ISSUE THREAD

**Issue by KifayatUllah** [wixtoolset/issues#5675]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
V3.10.2213.0
> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?
MS Visual Studio 2010
> (Visual Studio version, including year and update)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
V3.10
> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?
.Net Framework 4.0
> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Window 7, 10, 2012 server, etc
> (Windows version)

* Describe the problem and the steps to reproduce it.
Previous  version of program (which was installed with installshield installer) have added lots of required firewall exceptions. I have written new installer with Wix, and added firewall excpetion using firewall exception extension. it work fine on new install, however this new installer unable to overwrite firewall exceptions, I need this as file path is been changed and new files are located on different path.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

It should have changed target file path in window in bound and out bound exceptions 
> (Be as specific as you can and err on the side of providing too much information.)

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by barnson** [comment]
Please provide a verbose log showing the issue.

**Comment by urban-cookie** [comment]
@barnson: I am currently facing the same issue. It occurs when you are running the installer in repair mode (and probably in some upgrade scenarios) and try to change (or fix misconfigured) firewall exceptions. The problem is that the `FirewallException` does not account for changes of the ports, protocol, etc. The only thing it does is re-enabling the rule in case that it was disabled.

I had a quick look at the [source code for the `FirewallException`](https://github.com/wixtoolset/wix3/blob/develop/src/ext/FirewallExtension/ca/firewall.cpp). The issue is in [`AddPortException()`](https://github.com/wixtoolset/wix3/blob/bda1c281cb0349007d767d5404d6da87076d7d94/src/ext/FirewallExtension/ca/firewall.cpp#L586). Note especially the if-else-statement. In the else clause, the firewall rule is not updated according to the current properties (port, protocol, remote addresses, etc.). The issue still exists in WiX4.

Can you work with that information? The issue is actually already closed. Shall I open a new one in this case?

**Comment by barnson** [comment]
Yes, please open a new issue with the details. The code doesn't currently support what you're looking for but probably needs a new attribute to support both behaviors.

**Comment by EDLLT** [comment]
Any human being who faces this issue again the FIX is so simple, this thing got me pulling my hair OUT tryna fix it

First try to turn your firewall off, disconnect from the internet temporarily while doing so and check if it works, if it does then you gotta add a rule(you can search that up in google)

If that still doesn't work then turn your VPN off, my god damn VPN was causing all of these issues and I was pulling my hair out

If the above doesn't work then
open task manager(ESC + SHIFT + CTRL) , click the performance tab, open resource monitor and click the Network tab
Then in the "TCP Connections" tab look for any program that has the same port, in this case 3240 that's running, once you find it goto Task Manager find the same process name and terminate it(assuming that you couldn't close it safely)

Hopefully no one would face this issue again
