### ISSUE TITLE
Error 1311: Source file not found(cabinet) on Thai OS with Thai username

### ISSUE THREAD

**Issue by chris32888** [wixtoolset/issues#5682]
When the WiX installation media is copied onto the desktop of a Thai OS on windows 10 RS2 with a Thai username, this places the MSI and it's CABs in a path with Thai characters. When you try and then install the MSI, an error pops up "Error 1311: Source file not found(cabinet)". The path given where it is searching can be copy and pasted into an explorer window, where you can see that the cab is in fact there. If you do not have Thai characters in the username this issue cannot be reproduced.

Is this a WiX or Windows issue? No path to the cabs is provided in the WiX code, we rely on the default path to the cabinets, which is to just have them alongside the MSI.

WiX Toolset version: 3.11.0.1528
Visual studio version: VS2015 14.0.25431.01 Update 3
Wix Toolset ext. version: 0.9.21.62588

**Comment by barnson** [comment]
WiX isn't involved at runtime (unless you're using a WiX custom action). You might try embedding the cabs, to see if MSI is better at handling them embedded in the .msi.

**Comment by jozefizso** [comment]
We have similar bug report when Windows account name contains Turkish characters.

**Comment by BMurri** [comment]
I suspect in both cases that the MSI database's codepage is not set in a compatible way for the windows account's culture settings, and you're seeing the difference between what msft calls ANSI and OEM codepages.

That's not a WiX bug, but it MIGHT be addressable using WiX localization authoring.

This issue doesn't have enough details to determine if this is the case or not.

**Comment by jozefizso** [comment]
Yes, it's a strange behavior of Windows Installer. I didn't want to imply bug in Wix, I just wanted to add info that we happen to have issue with a system where special Turkish character was in the username.

PS: do you know if MSI can be authored in Unicode or UTF-8 to perhaps overcome this limitation?

We authored the MSI in default English codepage.

**Comment by BMurri** [comment]
Unicode is not officially supported, but it is possible to set the database codepage to utf-8. You can't set the summary information codepage to any Unicode anything (windows installer refused to even load the MSI file last time I tried).

If the set any codepage to zero, you get 7-bit ASCII. So what I do whenever I have Unicode-only localizations (or even a slight chance of one) is to ban anything except English strings from the summary information for all localizations (no matter what they were) and for all Unicode-only cultures I'd set the summary information codepage to zero and the database codepage to utf-8. All other cultures I'd set based on the tables on Microsoft's site.

I never thought to test using non-ASCII pathnames for the account profile directories, so I don't know if I was lucky or if what I did worked.

I'm mentioning past tense because for the past decade none of my clients using MSI files have wanted any localization at all.
