### ISSUE TITLE
When doing a major upgrade, files that have a lower file version in the upgrade setup get deleted, resulting in a broken installation

### ISSUE THREAD

**Issue by forbjok** [wixtoolset/issues#5774]
**Environment**
Windows 10 Pro v1709 build 16299.248
Wix v3.11.1
Visual Studio 2017 v15.5.7
.NET Framework 4.6

**Description**
When doing a major upgrade where the new version contains a .dll of the same name as one that existed in the previous version, with a lower File Version number, the file will disappear after upgrading, causing the product installation to be broken and the user having to manually run a Repair on it to fix it.
The MajorUpgrade "AllowDowngrades" attribute does not affect this.

This is not an issue that frequently comes up, since most of the time files in an upgrade will have the same or a higher version number, but in some cases it could - such as when having to downgrade a dependency for whatever reason.

Here's a minimal reproduction solution illustrating the problem.
[ReproSetup.zip](https://github.com/wixtoolset/issues/files/1774160/ReproSetup.zip)

It contains 2 mostly identical setup projects with the same upgrade code, but with different versions and a different version of a .dll.
Installing either one freshly (no upgrade) works fine, but upgrading from the "old" one to the "new" one results in the .dll disappearing.

**Comment by barnson** [comment]
That's Windows Installer behavior, not a WiX bug. MSI doesn't like to downgrade files.

**Comment by glen-nicol** [comment]
Forgive me, but Isn't this exactly the thing that you said should be [covered by Major upgrades](http://www.joyofsetup.com/2008/12/30/paying-for-upgrades/#cheap-and-easy)? We are now running into this with a .net application that uses a lot of nuget packages that are not easy to change the file version of because we aren't building them. This really seems like it is at least worth noting in the documentation since there seems to be plenty of places saying all should be well but then also plenty of cases where it obviously isn't as easy as major upgrade and forget it.
