### ISSUE TITLE
Add Wix Toolset Extensions for JetBrains Rider IDE

### ISSUE THREAD

**Issue by indeecev** [wixtoolset/issues#5793]
If this issue is a feature request:

* Add Wix Toolset Extensions for JetBrains Rider IDE. It will help to develop Windows Installer projects using Rider.

**Comment by threezool** [comment]
Any updates on this?

**Comment by robmen** [comment]
This issue is open and unassigned. That means it is waiting for someone to investigate the root problem, discuss possible solutions to that problem then implement the decided solution.

If you are interested in doing so yourself, our [developer documentation][devdoc] provides a great checklist for getting started.

If you are not interested then you are waiting for someone else to become interested. If this issue has been open for a long time then there probably isn't much interest in this particular issue. In that case, you'll want to consider how to motivate others to fix it for you. This is a pretty [good list of support options][support].

[devdoc]: http://wixtoolset.org/development/
[support]: https://www.firegiant.com/support-options/

**Comment by Bluejanis** [comment]
Shouldn't this be done by jetbrains?

**Comment by grinay** [comment]
I need this too.

**Comment by robmen** [comment]
This issue is open and unassigned. That means it is waiting for someone to investigate the root problem, discuss possible solutions to that problem then implement the decided solution.

If you are interested in doing so yourself, our [developer documentation][devdoc] provides a great checklist for getting started.

If you are not interested then you are waiting for someone else to become interested. If this issue has been open for a long time then there probably isn't much interest in this particular issue. In that case, you'll want to consider how to motivate others to fix it for you. This is a pretty [good list of support options][support].

[devdoc]: http://wixtoolset.org/development/
[support]: https://www.firegiant.com/support-options/

**Comment by rolandh** [comment]
This is a deal breaker for us. Is this being built?

**Comment by robmen** [comment]
This issue is open and unassigned. That means it is waiting for someone to investigate the root problem, discuss possible solutions to that problem then implement the decided solution.

If you are interested in doing so yourself, our [developer documentation][devdoc] provides a great checklist for getting started.

If you are not interested then you are waiting for someone else to become interested. If this issue has been open for a long time then there probably isn't much interest in this particular issue. In that case, you'll want to consider how to motivate others to fix it for you. This is a pretty [good list of support options][support].

[devdoc]: http://wixtoolset.org/development/
[support]: https://www.firegiant.com/support-options/

**Comment by rolandh** [comment]
Hi mr bot.

**Comment by robmen** [comment]
I don't understand how JetBrains revenue motivates those of us working on the WiX Toolset. Perhaps you meant to file the feature request with [JetBrains](https://www.jetbrains.com/)?

**Comment by rolandh** [comment]
My bad, I thought this was a Jetbrains repo as that is what I was searching for. I'll repost there.

**Comment by inforithmics** [comment]
Here is the Rider YouTrack issue to vote on.

Support WIX projects
https://youtrack.jetbrains.com/issue/RIDER-477

**Comment by wmanning** [comment]
Looks like Jetbrains has a fix for this issue in place 2020.1 EAP4.  Maybe close this issue?
