### ISSUE TITLE
WiX toolset does not install targets into Microsoft Build Tools 2017 folder

### ISSUE THREAD

**Issue by antrv** [wixtoolset/issues#5804]
* Which version of WiX are you building with?
3.11.1

* Which version of Visual Studio are you building with (if any)?

Microsoft Build Tools 2017 15.6.7

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

None

* Which version of .NET are you building with?

4.5.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows Server 2016 Nano (desktopless)

* Describe the problem and the steps to reproduce it.

I'm compiling project in WIndows Server 2016 Nano with Microsoft Build Tools 2017 installed.
Build failed with message:
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\WiX\v3.x\wix.ca.targets does not exist.

WiX toolset does not install extensions (*.target files) to MSBuild folder of Build Tools:
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\

* Describe the behavior you expected and how it differed from the actual behavior.

WiX toolset installs extensions (*.target files) to MSBuild folder of Build Tools:
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\

**Comment by NickNightingale** [comment]
I had the same problem, but I uninstalled the extension it from inside VS, then reinstalled and the targets had been created (VS 15.7.1).

**Comment by barnson** [comment]
WiX doesn't install targets files into any VS SKU. For VS SKUs that support extensions, the WiX VS extension will install "forwarding" targets. But the real targets are installed in a single per-machine location. For VS SKUs that don't support extensions, you need to modify existing .wixprojs to point to the per-machine location. The new .wixproj templates have that change already.

**Comment by bakerhillpins** [comment]
@barnson 
I'm Sorry but I've completely missed what you are trying to convey as a solution to this issue.

I've got a build server with VS2017 Build tools (15.7.5) and WiX 3.11 installed (after the build tools). The VS 2017 Extension 0.9.21.62588 (3/21/18) fails to install on that machine. Since it located the build tools and failed, WiX considers this an SKU that doesn't support extensions.
8/2/2018 6:10:28 PM - Found installed product - Visual Studio Build Tools 2017
8/2/2018 6:10:28 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

However, I have extensions from other vendors that install to the build tools just fine. Thus it would seem that the VS2017 Build Tools supports extensions no?

To your point about modifying projects:
Is the Per Machine location you are talking about located at %wix%? Though I'm trying to stop having to constantly hand edit project files to get past problems.

Also:
I've created new projects with the latest VS IDE and WiX 2017 extension and there are no differences in behavior on the build server. It continues looking for .targets files in the dir mentioned in the original post.  Can you please be more specific about "new .wixproj templates have that change already".  Seeing that the Extension (which is the latest released version at this time) predates your post by 2 months, this suggests I'm not able to get the most recent .wixproj files?

@antrv 
To follow up for the OP:
I simply went to a machine with the 2017 IDE (Enterprise) installed and copied the WiX dir (C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft) to the Build tools directory you mention and my build machine works now. I'd prefer to install tools but in the short term it beats installing the entire IDE onto our build machines or lots of hand editing.

**Comment by rseanhall** [comment]
This bug is not about WiX's VS extension. The OP was talking about the behavior of the WiX Toolset's installer.

WiX's VS extension has its own project system which requires it to depend on a lot more VS infrastructure than other extensions. VS does not support installing WiX's VS extension into their Build Tools SKU. See https://github.com/wixtoolset/issues/issues/5525 for more info.

IIRC, this bug is for adding the documentation around exactly what to fix in the .wixproj.

Creating new projects with the latest WiX VS extension and WiX 3.11 installed on the machine is supposed to work. Please contact the wix-users mailing list if you are still having issues.

**Comment by bakerhillpins** [comment]
@rseanhall 
Thanks, I see that I'm just not good at getting my point across, I guess that's why I was trying to direct my inquiry to barnson trying to understand his statements and the 2 .wixproj based solutions he mentioned. I.e. the Extension should install (or maybe shouldn't) and that the latest .wixproj files deal with this or edit the old ones. None were behaving the way that I read he suggested and since documentation is always the lowest priority I was hoping he could expand on the editing/updated .wixproj here in the issue so that those of us having the problem could get somewhere in the mean time.

Yes, some of my confusion is directed at the extension and my comment to the OP was to help him move forward because that's what I did so we could. Thanks for the link to the Extension issue, I will check that out.

**Comment by robmen** [comment]
@bakerhillpins, for support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

**Comment by cameron314** [comment]
Same thing with VS2019 build tools. I fixed it by changing my projects to match the new templates:

- For .wixproj files, I removed the following two lines:

      <WixTargetsPath Condition=" '$(WixTargetsPath)' == '' AND '$(MSBuildExtensionsPath32)' != '' ">$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets</WixTargetsPath>
      <WixTargetsPath Condition=" '$(WixTargetsPath)' == '' ">$(MSBuildExtensionsPath)\Microsoft\WiX\v3.x\Wix.targets</WixTargetsPath>

  and replaced the `<Import Project="$(WixTargetsPath)" />` with:

      <Import Project="$(WixTargetsPath)" Condition=" '$(WixTargetsPath)' != '' " />
      <Import Project="$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets" Condition=" '$(WixTargetsPath)' == '' AND Exists('$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets') " />
 
- For custom action project files, I removed the following line:

      <WixCATargetsPath Condition=" '$(WixCATargetsPath)' == '' ">$(MSBuildExtensionsPath)\Microsoft\WiX\v3.x\Wix.CA.targets</WixCATargetsPath>

  and replaced the `<Import Project="$(WixCATargetsPath)" />` with:

      <Import Project="$(WixCATargetsPath)" Condition=" '$(WixCATargetsPath)' != '' " />
      <Import Project="$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.CA.targets" Condition=" '$(WixCATargetsPath)' == '' AND Exists('$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.CA.targets') " />

This works because `MSBuildExtensionsPath32` is actually not a single path, but a sequence of paths that get searched during the `Import` process. The primary `MSBuildExtensionsPath32` is the VS2019 build tools MSBuild folder (which contains no WiX targets), but the secondary one is to the central `$(MSBuildProgramFiles32)\MSBuild` path, where WiX is installed. This can be seen by building with a verbosity of 'Detailed':

> Search paths being used for $(MSBuildExtensionsPath32) are C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild;$(MSBuildProgramFiles32)\MSBuild

**Comment by barnson** [comment]
Rob fixed in https://github.com/wixtoolset/web/pull/129.
