### ISSUE TITLE
The Wix element has an incorrect namespace of 'http://wixtoolset.org/schemas/v4/wxs'.  Please make the Wix element look like the following: <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">

### ISSUE THREAD

**Issue by abhisheknene007** [wixtoolset/issues#5967]
Hi Team,

I am getting below error continously.
i have tried reinstall wix toolset again.
also, i have changed given URL as per error and tried rebuilding the solution. still facing the same problem.

Can someone please help me into this.

Error line 
-  ****The Wix element has an incorrect namespace of 'http://wixtoolset.org/schemas/v4/wxs'.  Please make the Wix element look like the following: <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">****

Product.wxs file is building fine. Only file name with _ProjectName.wxs file which present in Harvested Output giving me error.

* Which version of Visual Studio are you building with (if any)?

- VS 2013

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

- 3.11 and 4.0 Wix toolset are installed. Although same versions and softwares installed on another machine and there it is working absolutely fine.

* Which version of .NET are you building with?

> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version) - Windows 10

* Describe the problem and the steps to reproduce it.

> When i rebuild the solution, i get this error from wix installer setup which i have created to generate msi.

* Describe the behavior you expected and how it differed from the actual behavior.

> Solution should build successful and it should create msi and it is working fine on other machines.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by abhisheknene007** [comment]
Hi rob, i have tried sending mail to wix user mailing list. it is getting bounce back.
if possible can you all please help me out here. it is urgent.

**Comment by BMurri** [comment]
Please make the effort to [subscribe](mailto:wix-users-request@lists.wixtoolset.org?subject=subscribe) to the wix-user mail list (messages from non-subscribed email accounts will be rejected, due to high spam levels).

Quite simply: Heatv4 cannot be used with Candlev3. You can't mix any WiX v3 and WiX v4 products in the same project.

Since you are building using WiX v3, make user that the harvester you are using is also from WiX v3. If you absolutely have to use v4's harvester (for whatever reason) you will want to transform the output to down-convert it to v3 syntax (WiX has no tools nor plans to create such a tool).

If you need more help, please [subscribe to wix-users](mailto:wix-users-request@lists.wixtoolset.org?subject=subscribe), and open a discussion there.

**Comment by abhisheknene007** [comment]
thanks for the details. @BMurri .

Got the version difference which i wasn't knew. It is resolved now.

**Comment by Adinihal** [comment]
> thanks for the details. @BMurri .
> 
> Got the version difference which i wasn't knew. It is resolved now.

**Comment by Adinihal** [comment]
Hi @abhisheknene007  could you please give the steps how you have port your wix 3.11 to wix 4 , i have a same requirement and the same error i am getting
