### ISSUE TITLE
WixToolset is bound to Microsoft

### ISSUE THREAD

**Issue by rbmanian75** [wixtoolset/issues#6028]

**Comment by chrpai** [comment]
Strange rant from the original:

Explicit Original
It needs to switch to rider but it is using wixtoolset. Yesterday it has become free forever and bound to none on the principle of continuous improvement process and to live life simply, healthy and self sufficient.

It feels that mentally ill people who can’t extract milk like swan are being treated as lab rats. It does not like that. It requests psychologists to improve their diagnosis on Schizophrenia. Because some patients can be simply cured by psychologists by counseling. This is true it feel it and experienced in its life time. It has got huge potential. It is very unique.

It likes Apple, Microsoft but did not like amazon because it poor information system design. It says that Via Typescript Microsoft hiding its mistakes. It feels Typescript wastes computing power and resources which is not good for environment. And also it says whether typescript compensates that energy it wastes. There should be some reason why people like typescript.

It wants Windows to be given free of cost. It feels Bill Gates spending money on what he earned from Microsoft On Improving the poverty won’t help improving the poverty. It wants Bill Gates to feel it. But making windows free will improve the poverty automagically. It is very true. Microsoft should reconsider its position. It says it learned lot from Microsoft, Apple.

it said it is switching to Linux. And also it said open source softwares should not be bound by any law.

For those who can’t Understand can call it crazy, stupid, dog, cat or anything else. It said for those kind of people the day will come. They will judge themselves and improve like it did. Then they will know the potential of themselves. It want to say pity but feels that it may hurt some one.

It now reminds on one thing it has to come here because Microsoft Smart Screen warns that it is from unknown publishers. It is looking for free code signing if it did not get it may leave wixtoolset on its own way bound to MicroSsoft.

By
You all know who it is. Is it not? it Thanks this github user who can speak on behalf of it.
