### ISSUE TITLE
MSI Security issues

### ISSUE THREAD

**Issue by benp87** [wixtoolset/issues#6036]
* Which version of WiX are you building with?

> 3.11.1

* Which version of Visual Studio are you building with (if any)?

> VS Professional 2017 - Version 15.9.12

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.9.21.62588

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 64 bit RS4

* Describe the problem and the steps to reproduce it.

> When creating an MSI using Wix, I have noticed some security issues after scanning the MSI.
> I have used the following applications to check and set security flags:
> https://github.com/NetSPI/PESecurity
> https://blog.didierstevens.com/2010/10/17/setdllcharacteristics/
> 
> I have checked the MSI using PESecurity and got the following output:
> 
> 
> FileName         : E:\NewFolder\MySetup.msi
> ARCH             : 57626
> DotNET           : True
> ASLR             : False
> DEP              : False
> Authenticode     : False
> StrongNaming     : N/A
> SafeSEH          : N/A
> ControlFlowGuard : False
> HighentropyVA    : False
>
> 
> As you can see, there are 2 issues here, the ASLR and DEP status (Authenticode can be solved using a digital signature).
> These 2 flags are being set to true using a compilation bits when building a .Net or C++ applications (ASLR is DynamicBase bit and DEP is NxCompat bit).
> But for some reason they are not set by Wix. I'm not sure if an MSI needs to flags or there is a real security issue here..
> 
> Setting those flags after the MSI is built sometimes works and sometimes the MSI gets corrupted.

* Describe the behavior you expected and how it differed from the actual behavior.

> I think these flags should be set when MSI is being built, maybe explicitly by configuring candle/light or by default.

**Comment by BMurri** [comment]
MSI files, while a binary format, are not PE files and cannot be loaded by Windows OS PE file loading APIs (e.g. CreateProcess, LoadLibrary). They are similar to, but not the same as, OLE Compound Files, and while not executable, may (but don't have to) contain executable files embedded within (just like ZIP files).

Since they are not PE files (and don't contain PE headers) those flags don't exist and a PE file checker scan is meaningless with regards to the MSI file types. Setting non-existent "flags" in an unrelated file type will simply corrupt the file.

**Comment by benp87** [comment]
In that case there is no issue.. Thanks :)
