### ISSUE TITLE
DTF vulnerable to "Zip Slip"

### ISSUE THREAD

**Issue by firegiantco** [wixtoolset/issues#6075]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

* Which version of WiX are you building with?

> WiX v3.11.1

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> Any

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> A maliciously crafted cabinet or zip file can be created with traversal paths in the archived file names. For example, `..\..\hackedu.dll`. DTF's `ArchiveFileStreamContext` will concatenate the archived file path with a provided base directory, such that the traversal path can place the file outside the provided base directory and possibly overwriting the user's files. This is known as [Zip Slip](https://github.com/snyk/zip-slip-vulnerability).

* Describe the behavior you expected and how it differed from the actual behavior.

> DTF should not write files outside the extraction folder.

> This issue was originally reported by Devin Casadey.

**Comment by YashvirGaming** [comment]
@robmen  fix your 6.0.2 man there is no **WixToolset.UI.wixext.dll**  , even i downloaded the nupkg renamed it to zip, extracted inside the bin folder but still can't use it been getting issues like 

: error WIX0094: The identifier 'WixUI:WixUI_InstallDir' is inaccessible due to its protection level.
error WIX0005: The Wix element contains an unexpected child element 'Product'.
error WIX0048: The document element name 'Package' is invalid. A WiX source file must use 'Wix' as the document element name.

error WIX0199: The Wix element has an incorrect namespace of 'http://schemas.microsoft.com/wix/2006/wi'. Please make the Wix element look like the following: <Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">.


for the WIX0199 i did changed & added this special line 
**<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">**

Still there are issues like : error WIX0094: 

Fix this god damn v6.0.2  man. This is so annoying , im going back to Inno Setup as this shit ain't working , added to PATH too in system variable Path etc done., but your thing isn't working, and you removed the ISSUES on this REPO why ?

Like to create Issues or open support issues, i have to find old threads. God damn it . FIX this @robmen
