### ISSUE TITLE
Not getting wix editor window in visual studio 2012. 

### ISSUE THREAD

**Issue by sahuajay86** [wixtoolset/issues#6100]
Not getting wix editor window in visual studio 2012. i had installed wix tool compatible VS-2012 several times to ride off this issue but not able to. please help.
![wixbug](https://user-images.githubusercontent.com/18568917/68950976-4122ed00-07e3-11ea-8ae9-5ca92af8c29c.jpg)

**Comment by barnson** [comment]
There is no WiX editor window. Perhaps you're thinking of a third-party tool?

**Comment by sahuajay86** [comment]
I am sending you image which i want to have. please check
![wixmenu](https://user-images.githubusercontent.com/18568917/68987947-aa434880-0855-11ea-9c26-628aef1716c2.jpg)

**Comment by barnson** [comment]
That's not something that comes with WiX. Perhaps you're thinking of a third-party tool?

**Comment by sahuajay86** [comment]
https://www.youtube.com/watch?v=4tZVFO0IwIM
please refer this video, for more info. it shows that with WIX it comes in solution explorer

**Comment by BMurri** [comment]
The provider of that video provides a link in the video description that takes you to what appears to be the third party tool the video describes that I assume you are seeking.

The URL is https://www.add-in-express.com/wix-designer/index.php

That UI does not ship with WiX. You have to purchase and install AddIn Express's VSIX in order to get that UI.
