### ISSUE TITLE
Wix installer keeps searching for file "desktop.ini"

### ISSUE THREAD

**Issue by benp87** [wixtoolset/issues#6119]
* Which version of WiX are you building with?
3.11.1

* Which version of Visual Studio are you building with (if any)?
Visual Studio 2019 16.4.1

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
1.0.0.4

* Which version of .NET are you building with?
4.6.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 7, 8, 10

* Describe the problem and the steps to reproduce it.
When I try to install using a Wix bundle, right after clicking the "Install" button I see that it tries to load a file called "desktop.ini", it searched for it in a lot of locations that are not part of the installation process, (I used Process Monitor to check this), is this normal? Should it do that? I think it's a security issue..

* Describe the behavior you expected and how it differed from the actual behavior.
I don't think that the installer should load files from a "random" locations in the system, maybe only the same directory as the installer or other secured directories (Like System32).

**Comment by robmen** [comment]
There is no code (that I'm aware of) in Burn that loads `desktop.ini` (or any `.ini` file for that matter) directly. It is entirely possible one of the Win32 APIs Burn uses to do its work touches `desktop.ini`. If you are interested in finding out, you should be able to step through Burn source code to track down what is touching `desktop.ini`.

You'll also notice that a Burn process will read hundreds (maybe thousands) of registry keys that having nothing to do directly with Burn. Again, Win32 APIs do lots of work to interact properly with Windows.

If you find that there is a problem in Burn due to access `desktop.ini` (or anything really, we're always interested in capturing all the problems that break Burn), do let us know.

**Comment by benp87** [comment]
Well, it seems that the function "ShellExecuteEx" (In shelutil.cpp) is the one that searches for “desktop.ini” when it is called. I have tried to change its parameters, so far no luck..

**Comment by robmen** [comment]
Glad you found the Win32 API. I guess it doesn't really surprise me that `ShellExecuteEx` takes a look at `desktop.ini`.
