### ISSUE TITLE
Burn Log element bug with Prefix

### ISSUE THREAD

**Issue by benp87** [wixtoolset/issues#6191]
* Which version of WiX are you building with?

> 3.11.2

* Which version of Visual Studio are you building with (if any)?

> VS2019 16.6

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.4

* Which version of .NET are you building with?

> 4.6.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 build 18362

* Describe the problem and the steps to reproduce it.

> I set the Bundle's Log element like this: 
>`<Log Prefix="[WixBundleProviderKey]\[WixBundleName]" /> `
But the logs are created into the file `"C:\Users\Ben\AppData\Local\Temp\[WixBundleProviderKey]\[WixBundleName]_20200621133636.log"`.
In the log I see that the variable WixBundleLog is: `"C:\Users\Ben\AppData\Local\Temp\{d07fba67-a337-457f-889c-cb67e0c98c8b}\Installer_20200621133636.log"`.
So the variable is set correctly but the log file is not created correctly..

* Describe the behavior you expected and how it differed from the actual behavior.
> Log path should be: `"C:\Users\Ben\AppData\Local\Temp\{d07fba67-a337-457f-889c-cb67e0c98c8b}\Installer_20200621133636.log"`.

**Comment by rseanhall** [comment]
This was first asked for in https://github.com/wixtoolset/issues/issues/3816

**Comment by benp87** [comment]
8 years ago? Is Wix not in development anymore?
Anyway, it's also a bug not just a feature, WixBundleLog is different from the actual log file.

**Comment by robmen** [comment]
@benp87, #3816 is open and unassigned. That means it is waiting for someone to investigate the root problem, discuss possible solutions to that problem then implement the decided solution.

If you are interested in doing so yourself, our [developer documentation][devdoc] provides a great checklist for getting started.

If you are not interested then you are waiting for someone else to become interested. Since this issue has been open for a long time then there probably isn't much interest in it. In that case, you'll want to consider how to motivate others to fix it for you. This is a pretty [good list of support options][support].

[devdoc]: http://wixtoolset.org/development/
[support]: https://www.firegiant.com/support-options/

**Comment by rseanhall** [comment]
Sorry, I skipped right over the bug part of this. We can use this issue to track Burn setting the `WixBundleLog` with the literal functionality added in https://github.com/wixtoolset/issues/issues/4763.

**Comment by rseanhall** [comment]
Fixed in v4 by https://github.com/wixtoolset/burn/pull/20.
