### ISSUE TITLE
Wix does not detect custom action schedule cycle and silently removes the custom actions

### ISSUE THREAD

**Issue by MikeRosoft** [wixtoolset/issues#6201]
Suppose that we have the following erroneous install sequence:
```
    <InstallExecuteSequence>
      <Custom Action="Action1" After="Action2" />
      <Custom Action="Action2" After="Action3" />
      <Custom Action="Action3" After="Action1" />
    </InstallExecuteSequence>
```

This is a cycle (first action is scheduled after the second, second after the third, and third after the first. Observed behavior on build of Wix project: All actions in the cycle, as well as any custom actions scheduled after them, are silently removed and do not appear in table `InstallExecuteSequence` (verify using Orca utility).

Expected behavior: Wix should detect the condition and report an error. ~~A case could be made that it should also warn if there is some custom action which is declared but not scheduled.~~ (Edit: this is a legitimate scenario, sequence can be modified by another custom action.)

Reproduced using Wix 3.14.0.3316. Also occurs when using Wix 3.11.

**Comment by rseanhall** [comment]
I added a failing test for this scenario. This would be a great first contribution to the toolset.

**Comment by robmen** [comment]
Note: Not all custom actions have to be scheduled in a sequence. It is common for custom actions to be inserted into the transaction script by another custom action (in the procedural code). For example, all WiX custom actions that modify machine state do this.

The fix is in `Core\src\WixToolset.Core.WindowsInstaller\Bind\SequenceActionsCommand.cs` to do a more thorough check in `ContainsChildActionSymbol()`.

**Comment by cpuwzd** [comment]
@rseanhall,

Please assign this issue to me.

Thanks.

Ron Martin
