### ISSUE TITLE
WiX v4 should have documentation

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#6213]
* Describe the scenario and benefits that the feature supports.

> Some people find documentation useful.

* Describe how you're accomplishing the feature today (if possible).

> Source code.

* Describe what you'd like the new feature to do.

> Provide useful information.

**Comment by danjagnow** [comment]
I was checking out [WiX Online Meeting #210 Highlights](https://www.firegiant.com/blog/2021/4/15/wix-online-meeting-210-highlights/), and it looks like WiX v4 Preview Zero is getting really close.  Is there a way to assist with compiling the documentation without deep knowledge of the changes since WiX 3?

**Comment by barnson** [comment]
At the moment, all that's really in the `doc` repo is building the .xsd schema file into readable doc. So far anyway -- getting that reference doc in place is the highest priority for Preview Zero. Unfortunately, that mostly means paging through the .xsds and comparing them against the compiler code to look for changes.

But there are also placeholders for other doc -- and the doc for v3 has a lot of additional topics that need to be updated for WiX v4. For example, all the "How-To Guides" need to be converted to WiX v4 and modernized (i.e., take advantage of features like automatic GUIDs and WiX's simplified directory handling). If you wanted to take a look at that, I'd be more than happy to review and edit!
