### ISSUE TITLE
System.OverflowException when calling Microsoft.Tools.WindowsInstallerXml.Unbinder.Unbind

### ISSUE THREAD

**Issue by GnI1991** [wixtoolset/issues#6299]
If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.1.2318

* Which version of Visual Studio are you building with (if any)?

> MSVS 2015 Version 14.0.25431.01 Update 3

* Which version of .NET are you building with?

> v4.5.2

* Describe the problem and the steps to reproduce it.

Currently, when we are trying to call “Microsoft.Tools.WindowsInstallerXml.Unbinder.Unbind” on a generated bundle, we get the following exception:
Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
   at Microsoft.Tools.WindowsInstallerXml.BurnCommon.ReadUInt32(Byte[] bytes, UInt32 offset)
   at Microsoft.Tools.WindowsInstallerXml.BurnCommon.EnsureNTHeader(BinaryReader reader)
   at Microsoft.Tools.WindowsInstallerXml.BurnCommon.GetWixburnSectionInfo(BinaryReader reader)
   at Microsoft.Tools.WindowsInstallerXml.BurnCommon.Initialize(BinaryReader reader)
   at Microsoft.Tools.WindowsInstallerXml.BurnReader.Open(String fileExe, IMessageHandler messageHandler)
   at Microsoft.Tools.WindowsInstallerXml.Unbinder.UnbindBundle(String bundleFile, String exportBasePath)
   at Microsoft.Tools.WindowsInstallerXml.Unbinder.Unbind(String file, OutputType outputType, String exportBasePath)

After debugging, I noticed that the exception is due to trying to read a checksum (this.Checksum = BurnCommon.ReadUInt32(bytes, IMAGE_OPTIONAL_OFFSET_CHECKSUM);).

Our bundle has the following bytes, as a checksum:
“byte[] bytes = { 0x23, 0xD6, 0x2A, 0x80 };”

* Describe the behavior you expected and how it differed from the actual behavior.

Expected behavior, would be: not getting such exception. But just to suggest possible fix: by playing around with the code of the
        private static UInt32 ReadUInt32(byte[] bytes, UInt32 offset)
        {
            Debug.Assert(offset + 4 <= bytes.Length);
            return (UInt32)(bytes[offset] + (bytes[offset + 1] << 8) + (bytes[offset + 2] << 16) + (bytes[offset + 3] << 24));
        }

function, I noticed, that the overflow results from the cast, and if I change such code to cast each term to Uint32, opposed to just casting the result, the exception seems to go away.

In my opinion, such error could result in any ReadUintXX function, since they seem to follow similar pattern.

**Comment by rseanhall** [comment]
Thanks. I can't believe this bug has been there this whole time.

**Comment by cpuwzd** [comment]
I can't say for sure, but I suspect that replacing the "+" operators with "|" operators might be a simpler way to fix this problem than casting each byte separately. If C# follows the lead of C and C++, it widens an unsigned 8-bit field to an unsigned 32-bit field, leaving open the possibility that an arithmetic shift rather than a logical shift would propagate ones to the left, rather than zeroes. This is an area where I wouldn't blindly trust the good intentions of a compiler writer. My apologies if I'm way off base, but I thought I thought it would be better to pass this thought along, rather than ignoring it. I didn't see anyone else comment on why the questioned code failed to perform as expected.
