### ISSUE TITLE
In BootstrapperApplicationData.xml, Package/@Compressed is wrong

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6371]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> Latest v4.

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> When building a bundle without specifying `Bundle/@Compressed`, each package is defaulted to `yes`. But in BootstrapperApplicationData.xml, it is set to `no`. (Everything else is properly handling the package as compressed)

* Describe the behavior you expected and how it differed from the actual behavior.

> See failing test at https://github.com/wixtoolset/Core/blob/a13f13130b84845fed54f812e2ad33136c7649cb/src/test/WixToolsetTest.CoreIntegration/BundleManifestFixture.cs#L55. Note that test is also failing due to #6372.

**Comment by robmen** [comment]
The `Package/@Compressed` attribute is forced to 'no' because the `ExePackage` is remote. This makes sense since remote `ExePackage`s do not exist locally so they cannot be compressed in a container. Thus they are always forced to `Compressed='no'`.

The test is using the old `Remote` element so I can update the test to the new `ExePackagePayload` syntax and fix the `Compressed` expectation.
