### ISSUE TITLE
Visual Studio 2022 integration?

### ISSUE THREAD

**Issue by nbelyh** [wixtoolset/issues#6493]
Visual Studio 2022 integration does not seem to be available (yet?)
Would be nice to have it by the time 2022 is released.

Since it's x64, probably, there may be some issues.

Or maybe I am missing something?

**Comment by BMurri** [comment]
The WiX Toolset team has traditionally tried to time its releases to be near the public production release of the associated tool (so, usually not previews).

**Comment by ChrisShawK2** [comment]
Understood.
If a 'preview' version could be available earlier, though (even if only to let me load -- not run -- WiX projects), I'd install it right away, and then the real one when available...?

**Comment by rkieslinger** [comment]
Will Visual Studio 2022 integration support wix v3.xx?

**Comment by robmen** [comment]
Not yet. It is not common for us to push to get Votive released ahead of VS RTM. But [this PR](https://github.com/wixtoolset/VisualStudioExtension/pull/21) is promising.

**Comment by drolevar** [comment]
@robmen Do you have an idea whether wix3 will be patched to support VS2022? If you can think of releasing an updated version of wix3, I could think of doing this.

**Comment by sfullerbeckman** [comment]
When is the Visual Studio 2022 Wix extension going to be released? Visual Studio 2022 was released [today](https://visualstudio.microsoft.com/launch/).

**Comment by robmen** [comment]
@sfullerbeckman Soon.

**Comment by drolevar** [comment]
@sfullerbeckman The Visual Studio SDK Nuget package is still in a preview state. So I'll wait until they issue a release version and then update this PR.

**Comment by danlyons-softek** [comment]
@drolevar Amusingly, it looks like the [Visual Studio SDK Nuget package](https://www.nuget.org/packages/Microsoft.VisualStudio.SDK) added a release version not long after your comment.

**Comment by FG-rgb** [comment]
Still no update. When does there will be a release for the VS2022 Wix extension?

**Comment by robmen** [comment]
Soon

**Comment by frozenprakash** [comment]
Started a branch to test with Visual studio installer.

Not to discredit the Wix team, but in future this will be holding back my projects for several months before every future Visual studio releases.

**Comment by drolevar** [comment]
@frozenprakash Not to discredit you, but to you really plan on moving from WiX to .vdproj-based Visual Studio Installer? Or did I misunderstand you?

**Comment by mortenn** [comment]
@frozenprakash, in my opinion, if being able to use preview releases of VS is so important to you, then you should definitely use visual studio installer rather than wix toolset anyway.

While I personally do wish wix toolset would have worked in the 2022 preview so I could have used it for all the solutions I work on, it doesn't seem that critical to me.

**Comment by frozenprakash** [comment]
@mortenn True that. I should had had an alternative installer to use during these needed situations.

**Comment by frozenprakash** [comment]
> @frozenprakash, in my opinion, if being able to use preview releases of VS is so important to you, then you should definitely use visual studio installer rather than wix toolset anyway.

True that. I should had had an alternative installer to use during these needed situations.

**Comment by frozenprakash** [comment]
> @frozenprakash Not to discredit you, but to you really plan on moving from WiX to .vdproj-based Visual Studio Installer? Or did I misunderstand you?

Yes. 
As usually during VS upgrade, I start the migration process fixing things couple of months in preview itself, so that I keep my solution compatible with new version right off the bat once full version is released.

**Comment by fforjan** [comment]
Note that there is a difference in the editor and the toolset.  In our case, we are usually trying to upgrade the editor first and keep our build machine with previous version. When everything seems good then we upgrade the build machine to the newer version. 
In our team, usually we also start the preview of the editor to see what would be any impact in our workflow, we have been creating .vsconfig install file for the developers since preview 1 and some developers have migrated fully on VS2022 with the preview one. 

We are not blocked for us as the developer can still use VS2019 to do any installer work if required, same as our build machine.
I do not think it would be a critical item as in our case no developer should ever generate an installer as it is only produced by our build machines.

**Comment by sfullerbeckman** [comment]
I am blocked as a developer from using VisualStudio 2022 until Wix is supported.

**Comment by gmichaud** [comment]
@sfullerbeckman you can build the integration yourself from the PR -- https://github.com/wixtoolset/VisualStudioExtension/pull/21

**Comment by sfullerbeckman** [comment]
@gmichaud , how would I do that? Are there any tutorials for how to?

**Comment by gmichaud** [comment]
@sfullerbeckman instructions in the link above. Right here: https://github.com/wixtoolset/VisualStudioExtension/pull/21#issuecomment-941993603

**Comment by FG-rgb** [comment]
> @sfullerbeckman instructions in the link above. Right here: [wixtoolset/VisualStudioExtension#21 (comment)](https://github.com/wixtoolset/VisualStudioExtension/pull/21#issuecomment-941993603)

I got it running, after several steps.
Important is to fix strong-name problems by using this article:
https://wixtoolset.org/development/building-wix/

**Comment by mortenn** [comment]
I just tried doing that myself, but it can't find "\bin\sn.exe" and the building-wix documentation page does not mention this executable.

```
Build started 10/11/2021 15:42:28.
Project "C:\github\VisualStudioExtension\tools\OneTimeWixBuildInitialization.proj" on node 1 (default targets).
C:\github\VisualStudioExtension\tools\OneTimeWixBuildInitialization.proj(30,5): error : Could not find sn.exe. Expected to find it at: \bin\sn.exe
Done Building Project "C:\github\VisualStudioExtension\tools\OneTimeWixBuildInitialization.proj" (default targets) -- FAILED.
```

**Comment by FG-rgb** [comment]
> I just tried doing that myself, but it can't find "\bin\sn.exe" and the building-wix documentation page does not mention this executable.
> 
> ```
> Build started 10/11/2021 15:42:28.
> Project "C:\github\VisualStudioExtension\tools\OneTimeWixBuildInitialization.proj" on node 1 (default targets).
> C:\github\VisualStudioExtension\tools\OneTimeWixBuildInitialization.proj(30,5): error : Could not find sn.exe. Expected to find it at: \bin\sn.exe
> Done Building Project "C:\github\VisualStudioExtension\tools\OneTimeWixBuildInitialization.proj" (default targets) -- FAILED.
> ```

Dit you run it with Developer command prompt for visual studio... x86 and "elevated"?

**Comment by echalone** [comment]
> 
> 
> Soon

We're stopped from upgrading to Visual Studio 2022 because of this missing extension. Would be nice to really have it soon... a lot of people are waiting ;)
And to be honest... there was a preview out for quite some time... not entirely sure why you couldn't have just prepared the extension for your customers so we can actually use Visual Studio 2022 when it arrives.

**Comment by robmen** [comment]
To be clear, none of my customers have asked for Visual Studio 2022 support. If you are a customer, please do [open a support ticket](https://support.firegiant.com/) so we know to prioritize VS2022 work with the other things we are doing for all of our customers.

If you're not a customer then you are a user. From users, we very much appreciate solid bug reports. We also appreciate users voting (👍🏻  is a good option) on open bug reports to help us see what is most interesting for people to work on. Finally, we also appreciate users that want to work and become contributors to directly help us improve the WiX Toolset.

But if you are simply a user (not a customer nor a regular contributor) then please do not make demands or suggest that those of us that do contribute spend our free time working on something that you get for free simply because you depend on it.

If the WiX Toolset is so important to you then become a customer or a contributor. Otherwise, as a user, wait while the contributors and customers carry the weight for you.

**Comment by Gakk** [comment]
Am I missing something, is not this a free open source project that everyone can contribute to?

I have also upgraded to VS2022, and started to use this for our projects since first preview. Since different versions of VS installs side-by-side I have no trouble opening VS2019 whenever there are changes that involve installer.

Not even a big and expensive product like JetBrains ReSharper managed to be ready in time for VS2022 (even though that is more annoying since we are paying a license for their product).

I have no problem giving the maintainers a little more time. I have read through every two-week developer meeting note since first preview of VS2022 and know they are working hard towards.

Keep up the great work! 😃👍

**Comment by gmichaud** [comment]
@Gakk amen! It's also very easy to build the add-in from the VS2022 dev branch (one needs to read the instructions in the PR [here](https://github.com/wixtoolset/VisualStudioExtension/pull/21#issuecomment-941993603))

Keep up the great work Wix team!

**Comment by mortenn** [comment]
> a) Dit you run it with Developer command prompt for visual studio... x86 and "elevated"? b) https://stackoverflow.com/questions/1535871/cannot-find-sn-exe-to-sign-assembly

I do not have the Windows SDK installed, so that should be the cause.

**Comment by echalone** [comment]
> I have also upgraded to VS2022, and started to use that for our projects since first preview. Since different versions of VS installs side-by-side I have no trouble opening VS2019 whenever there are changes that involve installer.
 
We have problems with side by side installation of VS 2019 and VS 2022 because we need to tell nuget to use the VS 2019 MSBuild instead of the autodetected VS 2022 MSBuild. But when we provide the VS 2019 MSBuild.exe path to nuget via parameter -MSBuildPath this error gets thrown during restore of the Wix project:
```
<PathToWixProjFile>\Example.wixproj : error MSB4057: The target "_IsProjectRestoreSupported" does not exist in the project.
```
I have created a bug report for this issue here: https://github.com/wixtoolset/issues/issues/662

**Comment by CyberSinh** [comment]
@barnson , do you know when the extension will be available to download? Thanks.

**Comment by barnson** [comment]
@CyberSinh : Please see the many, many, many comments above that address your question.

**Comment by CyberSinh** [comment]
So there's no more specific date than "soon" to look forward to?

**Comment by StevenRasmussen** [comment]
It's closer now than the last time they last said it 😉.  Please everyone stop asking the same question and spamming everyone.  Everyone here wants it, and they know that everyone here wants it, and asking them "when" will not speed things up.  If they want to give a date then I'm sure they'll post it here... but in the mean time be patient and I'm sure that they will deliver it as soon as they can.  Thanks WIX team for your efforts!

**Comment by frozenprakash** [comment]
@CyberSinh As explained earlier, this is not a paid product and we can't ask anyone to finish the work quickly as everyone is contributing as much as they can in their leisure time.

I hope we respect them for the amount of work they did until now as open source developers and just wait it out.

Probably end of this year, I hope we will be getting the new version.

Also as alternative as someone highlighted above,
I am now Opening the same solution in VS2019 & VS2022 side by side, 
And use VS2022 to do all coding work, and use VS2019 for building with old wix which works flawlessly.

**Comment by barnson** [comment]
@StevenRasmussen, actually I wanted to delay the release for at least 24 hours for every time someone asks, but Rob said that was mean.

**Comment by robmen** [comment]
Let me [reiterate](https://github.com/wixtoolset/issues/issues/6493#issuecomment-965493278):

> none of my customers have asked for Visual Studio 2022 support. If you are a customer, please do [open a support ticket](https://support.firegiant.com/) so we know to prioritize VS2022 work with the other things we are doing for all of our customers.
> ...
> If the WiX Toolset is so important to you then become a customer or a contributor. Otherwise, as a user, wait while the contributors and customers carry the weight for you.

[And](https://github.com/wixtoolset/issues/issues/6493#issuecomment-964095016):

> Soon

**Comment by robmen** [comment]
[WiX Toolset Visual Studio Extensions v1.0.0.12](https://github.com/wixtoolset/VisualStudioExtension/releases/tag/v1.0.0.12) now includes support for Visual Studio 2022. Huge thanks to @drolevar for [implementing the fix](https://github.com/wixtoolset/VisualStudioExtension/pull/21).

After we get validation from the community that v1.0.0.12 works in all versions of Visual Studio (2010-2022), we'll start the process to publish to Visual Studio Marketplace.

**Comment by davidnmbond** [comment]
Visual Studio 2022 Community (Current) crashes and reloads for me when when building a simple wixproj on Windows 11 insider (latest).

I'm getting "Could not load file or assembly 'file:///C:\Program Files (x86)\WiX Toolset v3.11\bin\Heat.exe' or one of its dependencies.  An attempt was made to load a program with an incorrect format." 

The heat.exe file IS present at the location.  A "repair" of the .exe installer v3.11.2 makes no difference.

**Comment by StevenBonePgh** [comment]
@davidnmbond Please see my comment at https://github.com/wixtoolset/VisualStudioExtension/pull/21#issuecomment-954301018
I have proposed some changes and give a workaround, and have not heard from any of the maintainers regarding the approach they would accept a PR for. Since writing the above, I saw some additional guidance in the .NET Blog [MSBuild and 64-bit Visual Studio 2022](https://devblogs.microsoft.com/dotnet/msbuild-and-64-bit-visual-studio-2022/) , where the [wix.targets](https://github.com/wixtoolset/wix3/blob/develop/src/tools/WixTasks/wix.targets) could be altered to specify `Architecture="x86"` for any MSBuild tasks that absolutely must be implemented as x86 only.

**Comment by davidnmbond** [comment]
@StevenBonePgh THANK YOU!  A workaround, not a fix, but it did work.

For others suffering the same issue, here is what you should do until there is a fix:
1. Right click on your Setup Project
2. Unload Project
3. Ctrl+F HeatDirectory
4. Add an attribute: RunAsSeparateProcess="true"
5. Right click on your Setup Project
6. Reload Project

**Comment by robmen** [comment]
Please open a new issue for this heat.exe problem. It isn't a Votive problem.

**Comment by echalone** [comment]
> [WiX Toolset Visual Studio Extensions v1.0.0.12](https://github.com/wixtoolset/VisualStudioExtension/releases/tag/v1.0.0.12) now includes support for Visual Studio 2022. Huge thanks to @drolevar for [implementing the fix](https://github.com/wixtoolset/VisualStudioExtension/pull/21).
> 
> After we get validation from the community that v1.0.0.12 works in all versions of Visual Studio (2010-2022), we'll start the process to publish to Visual Studio Marketplace.

It works for us, we're not using the HeatDirectory feature though. Thanks for the swift response and support of VS 2022! And sorry for any impatience on our "user" side ;)

**Comment by barnson** [comment]
Votive 2022 is not needed in a CI image. And WiX support is coming: https://github.com/appveyor/ci/issues/3754

**Comment by thompp** [comment]
While testing with VS2022, am using wix to install a product that integrates with Visual Studio.  It appears the properties to detect if VS2022 is installed are not yet implemented.  I'm referring to the properties listed at https://wixtoolset.org/documentation/manual/v3/customactions/wixvsextension.html.  Should that be logged as a separate issue?

**Comment by drolevar** [comment]
@thompp Here is the commit which adds VS2019 support: wixtoolset/wix3@3cc4b532e798ff9933965e38a96594f45fdeaf29
As you can see, it's implemented in the WiX toolset itself, and not in the VS extension.

**Comment by thompp** [comment]
@drolevar does not look confusing at all.  I think you are suggesting open this as a separate issue for VS2022 support in wix3 as maybe this issue is just around the integration via votive.

**Comment by demidov71** [comment]
I'm sorry to hit a nerve...
Ok, I want to support the project financially. How? Do you have a donation link?

**Comment by asm-flairstech** [comment]
Thank you

**Comment by robmen** [comment]
@demidov71 I think [you are referring to your comment on the other VS2022 support issue](https://github.com/wixtoolset/issues/issues/6673#issuecomment-994030063). You did two things in that comment:

> .NET 6 is available only on VS2022. Absence of WiX extension for it, hampers the development all over the world. Seriously, guys, leave the sofa!

First, you tried to guilt us into doing work for you. Second, you insulted us by suggesting we are lazy. You might consider apologizing to the people who actually work on the project instead of hinting that we shouldn't be offended by being insulted with: 

> I'm sorry to hit a nerve...

[FireGiant provides commercial support for the WiX Toolset](https://www.firegiant.com/services/support-programs/) and provides guarantees on bug fixes (primarily targeted at corporate customers). You could go that route to become a customer instead of just a consumer.

We do not accept donations on the WiX project today because donations have not been shown to be a financially sufficient mechanism to fund software development.

**Comment by vivekvdj** [comment]
Hi Team,

May I know when the link (https://wixtoolset.org/documentation/manual/v3/customactions/wixvsextension.html) will be updated with VS2022 properties? We have one of the installers which is a plugin to Visual studio. and we need these properties to be updated in the installer Wix solution Please let us know the tentative date when it will be available? 

Thanks.

**Comment by rseanhall** [comment]
This issue was for WiX's own extension for Visual Studio. You are looking for https://github.com/wixtoolset/issues/issues/6727.

**Comment by fartwhif** [comment]
installed WiX v3 - Visual Studio 2022 Extension
my WiX v3.11 setup project is incompatible with Visual Studio 2022

what gives?

**Comment by nbelyh** [comment]
@fartwhif you are doing something wrong. This issue was about supporting visual studio 2022, and it has been fixed long ago. In your place I would create a question on stackoverw under tag wix giving your problem details.
