### ISSUE TITLE
Port WixStdBA "files in use" page to Wix4

### ISSUE THREAD

**Issue by gvkries** [wixtoolset/issues#6545]
I just noticed that the "files in use" page of the standard BA was never ported to Wix4. I think this feature is still very important and it should be ported over to v4.

**Comment by rseanhall** [comment]
At that time, I was cherry picking almost everything from v3 to v4 but didn't do it for this because it was non-trivial for a couple reasons:
* I thought it should be a modal dialog instead of another page
* Breaking changes to thmutil schema

Since then, there are a couple more reasons not to port it directly:
* https://github.com/wixtoolset/issues/issues/5208 (the UI seems to be confusing when not using Restart Manager)
* Burn probably should be sending files in use messages differently to the BA - http://lists.wixtoolset.org/pipermail/wix-devs-wixtoolset.org/2020-May/001534.html

**Comment by gvkries** [comment]
Thanks for taking the time to look at this.

Yes, I remember some discussion about the differences when MSI is using restart manager or not. But since then I am not sure this is still a problem. I have never seen anyone turn of restart manager, and I guess support for Windows XP is not a priority anymore?

From the user experience perspective, I would really push back against having this displayed as a modal dialog. I don't think it is a good behavior opening dialogs from other dialogs. Don't get confused because I called it "modal" in code, that was probably not the best name... 

Anyway, whether porting it directly from Wix3 or not is of cause up to you. I just wanted this feature is not forgotten about because we still require it.

**Comment by barnson** [comment]
Restart manager can be turned off and it's something some people do to try to avoid files-in-use prompts.

**Comment by barnson** [comment]
As this was added during v3.x, it was opt-in (`ShowFilesInUse`). That's not necessary in v4.0 but should there be an opt-out? Triage team, you're our only hope.

**Comment by barnson** [comment]
"No."
