### ISSUE TITLE
WixUIExtension should support native platforms for custom actions

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#6612]
* Describe the scenario and benefits that the feature supports.

> WixUIExtension contains two custom actions that are called via `DoAction`: `WixUIPrintEula` and `WixUIValidatePath`. They should be platform-specific.

* Describe how you're accomplishing the feature today (if possible).

> Today, dialog sets are referenced via `UIRef`, so the x86 custom actions are used, relying on emulation on x86/ARM64.

* Describe what you'd like the new feature to do.

> The authoring needs to be refactored and a compiler extension added so the `-arch` can be used in referencing the custom actions. Maybe it could be done in another way but nothing comes to mind.

**Comment by rseanhall** [comment]
I think this had `wip-required` because there were design considerations.

1. Is it a good thing or bad thing that straight `UIRef` (unconverted v3 code) will still build in v4 but fail at runtime?
2. What is the official way to customize the UI dialog sequence now? Since the previous way will not bring in the custom action references, unless you create your own extension.
3. Why was the `WixUI_Mode` property removed?

**Comment by barnson** [comment]
Whoever added `wip-required` was nuts.

1. It will fail at build time.
2. The `WixUI` element also pulls in custom `UI` fragments.
3. Because it's no longer needed and shouldn't be persisted in the output.

**Comment by rseanhall** [comment]
1. Ah, the `DoAction` creates a simple reference to the `CustomAction` so it fails.
2. So without the compiler extension creating the `CustomAction`, the build will fail yes? So when creating a custom sequence, they'll have to author the `CustomAction` themself?
3. I thought that maybe people could be using that property, so pulling it would break them.

**Comment by barnson** [comment]
1. Right.
2. If today you use `<UIRef Id="BobsAwesomeUI" />`, now you can use `<ui:WixUI Id="BobsAwesomeUI" />` and it'll work the same way.
3. Semver FTW!
