### ISSUE TITLE
Can PackagePayloads be verified differently from "child" Payloads?

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#6802]
**Encountered at:** wixtoolset/wix4@a2d9a62

**Detail:**

If an XxxPackagePayload is being validated by a hash should a "child" Payload be allowed to be validated via Authenticode signature? For example:

    <ExePackage>
      <ExePackagePayload Name='foo.exe' Hash='abcdef' Size='1234' ... />
      <Payload Name='foo.cab' CertificatePublicKey='a1b2c3d4' CertificateThumbprint='e5f6123' Size='4321' ... />
    </ExePackage>

Similarly, if an XxxPackagePayload is being validated by certificate can the other Payloads be validated by hash? For example:

    <ExePackage>
      <ExePackagePayload Name='foo.exe' CertificatePublicKey='a1b2c3d4' CertificateThumbprint='e5f6123' Size='1234' ... />
      <Payload Name='foo.cab' Hash='abcdef' Size='4321' ... />
    </ExePackage>

**Comment by BMurri** [comment]
Sorry I missed the meeting yesterday.

My take: every payload item is validated via hash unless explicitly tagged otherwise. I wouldn't expect validation methodology to flow from one file to another, no matter how those files were associated.

Then again, I've been told I think differently than other, YMMV

**Comment by rseanhall** [comment]
v4 already requires hash validation when the source file was given during the build, it's not like where v3 where you can opt-in to the certificate information getting harvested at build time. `EnableSignatureVerification`/`DisableSignatureVerification` doesn't exist in v4. It only allows Authenticode verification if it's a "RemotePayload" (XxxPackagePayload with certificate information). So it's already doing what you're saying.

This issue was raising the question of whether packages should require all of its payloads to use the same verification method. The problem that could arise with mixed verification methods is that when multiple bundles have the same package with the same CacheId and the same payloads, but some payloads are verified differently, then it's possible for one bundle to cache files that other bundles will view as corrupt.

**Comment by BMurri** [comment]
IMHO each bundle should validate its own cache (because ultimately it owns its source of truth). If other bundles must validate caches they don't own, then the parameters of the cache validation need to be made available. It's not practical to make all payloads share any single method (except possibly hash).
