### ISSUE TITLE
HeatWave Conversion skips reference

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#6994]
* Which version of WiX are you building with?

wix 4 preview 1 and heatwave 0.9.0.5

* Which version of Visual Studio are you building with (if any)?

vs 2022 17.3.4

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
1.0.0.18 but probably not applicable

* Describe the problem and the steps to reproduce it.

I used HeatWave to convert a v3 wixproj to v4.  It converted the IIS, NetFx and UI wixexts but not WiXVSExtension.  It did update the vs namspace and vs:FindVisualSudio elements.   Once the reference was fixed everything compiled and the custom action successfully ran during the install.

* Describe the behavior you expected and how it differed from the actual behavior.

I expected to see WiXToolset.VisualStudio.wixext in the WiX Extensions dependencies.

**Comment by robmen** [comment]
This is an issue in HeatWave. FireGiant tracks HeatWave bugs in the newly created [HeatWave Support issues repo](https://github.com/firegiant/HeatWaveSupport). I can get this issue ported for you if you'd like. However, if you'd like the honor of being the first person to open an issue against HeatWave Support, this would definitely qualify. 😄 

I'm resolving this issue here and will wait a bit to see @chrpai chooses to open the issue before getting it opened.
