### ISSUE TITLE
VS Intellisense not working with HeatWave

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#7001]
## Feature requests

If this issue is a feature request:

Votive in v3 had intellisense in Visual Studio.  Using VS 2022 17.4 and HeatWave 0.9.0.5  I'm not getting intellisene suggestions for documents with the http://wixtoolset.org/schemas/v4/wxs namespace.

**Comment by chrpai** [comment]
I see the files installed to C:\Program Files\Microsoft Visual Studio\2022\Community\Xml\Schemas  so maybe this is a bug. I'm not sure why I'm not getting intellisense.

**Comment by chrpai** [comment]
I'm not getting intellisense for v3 projects either so maybe this is just something wrong with my machine.  Can anyone else reproduce?

**Comment by robmen** [comment]
This is an issue in HeatWave. FireGiant tracks HeatWave bugs in the newly created [HeatWave Support issues repo](https://github.com/firegiant/HeatWaveSupport). I can get this issue ported for you if you'd like. However, if you'd like the honor of being the first person to open an issue against HeatWave Support, this would definitely qualify. 😄 

I'm resolving this issue here and will wait a bit to see @chrpai chooses to open the issue before getting it opened.

**Comment by chrpai** [comment]
https://github.com/firegiant/HeatWaveSupport/issues/1
