### ISSUE TITLE
wix toolset upgrade failed on vs2022 pro

### ISSUE THREAD

**Issue by lzrdig** [wixtoolset/issues#7016]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> Wix 3.11.2.4526

* Which version of Visual Studio are you building with (if any)?

>VS2022 Version 17.4.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10; Pro Version 22H2; OS Build 19045.2251

* Describe the problem and the steps to reproduce it.
Was prompted to update the extension for Wix, which had already been present in VS2022 and was running fine.
The VSIX for the extension start fine, but it showed first that the signature is Invalid. Then, after continuing with the installation process it failed.

After multiple attempts to update all available certificates that I could guess are part of the certification chain I still cannot install the extension.
Browsing through the code source did not result in finding a Wix specific .cer file.

See the attached installation output log file.
[Wix3_VS2022_Failed_Install.txt](https://github.com/wixtoolset/issues/files/10005434/Wix3_VS2022_Failed_Install.txt)

Just a note: the log file mentions :  Unable to load extension at: C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\LINUX\LINUX\. Exception text: Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: The extension manifest file must be named 'extension.vsixmanifest'.

The file is present and it is in the correct format

**Comment by robmen** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com

This case most often happens when your root certificates have not been updated by Windows for a while (like in offline machines).
