### ISSUE TITLE
Wix Convert doesn't convert custom scheduling of WixCloseApplications

### ISSUE THREAD

**Issue by MBroholmA** [wixtoolset/issues#7018]
* Which version of WiX are you building with?
4.0 preview 1

* Which version of Visual Studio are you building with (if any)?
2022 17.3.6

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
Heatwave 4.0 preview 1

* Describe the problem and the steps to reproduce it.
A reschedule of WixCloseApplications action doesn't get converted to Wix4CloseApplications_X64

We have this fragment to reschedule the action:
```
    <InstallExecuteSequence>
      <Custom Action="WixCloseApplications" Before="StopServices" />
    </InstallExecuteSequence>
```

* Describe the behavior you expected and how it differed from the actual behavior.
This is left as-is, but should be:
```
    <InstallExecuteSequence>
      <Custom Action="Wix4CloseApplications_X64" Before="StopServices" />
    </InstallExecuteSequence>

```

**Comment by barnson** [comment]
The converter can't convert the custom action id because it's dependent on the build platform. The default scheduling correctly handles the prefix and suffix but when you override the scheduling, you'll have to handle that manually (for now, at least).

I'll add an appropriate warning to the converter.
