### ISSUE TITLE
Conversion references wrong package name for the Visual Studio Extension

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#7099]
vs 17.4.1
hw 0.9.1
wix 4 rc1

Create a setup project that uses the VS extension.  Upgrade it to WiX v4.  The build will fail saying:

Severity	Code	Description	Project	File	Line	Suppression State
Error	WIX0200	The Package element contains an unhandled extension element 'FindVisualStudio'. Please ensure that the extension for elements in the 'http://wixtoolset.org/schemas/v4/wxs/vs' namespace has been provided.	ProductName2	C:\GitHub\MusicKiosk\ProductName2\ProductName2\Code\Product.wxs	30	

Nuget shows errors.  Upon further examination it is noted that it's looking for WixToolset.VS.wixext Version 4.0.0-rc.1. The package is actually published as WixToolset.VisualStudio.wixext.

**Comment by robmen** [comment]
FireGiant's HeatWave handles the project-level conversion. FireGiant tracks HeatWave issues on the [HeatWaveSupport repo](https://github.com/firegiant/HeatWaveSupport). This appears to be another facet of https://github.com/firegiant/HeatWaveSupport/issues/2 that seems to be fixed in HeatWave v0.9.2.
