### ISSUE TITLE
Multiple problems with WixToolset UI 4.0.0

### ISSUE THREAD

**Issue by NilsHoyer** [wixtoolset/issues#7105]
FireGigant HeatWave for VS2022 0.9.1
WixToolset.UI.wixext 4.0.0-rc.1

I hope, I'm right here?

I try to build my first Wix project. It should have standard UI dialog, but now license agreement. For this, I try the following code.

But VS 2022 tell me, that  `Condition` attribute is not declared.

Additionally, I have an unexpected error in the ResolvePackageDependencies task (MSB4018).

And at the end, ICE17 PushButton: 'Print' of Dialog: LicenseAgreementDlg' does not have an event defined in the ControlEvent table. It is a 'Do nothing button. (WIX0204).

    <?xml version="1.0" encoding="UTF-8"?>
    <Wix
        xmlns="http://wixtoolset.org/schemas/v4/wxs"
        xmlns:ui="http://wixtoolset.org/schemas/v4/wxs/ui">

        ...

        <UI>
                <UIRef Id="WixUI_InstallDir" />
                <Publish Dialog="WelcomeDlg" Control="Next" Event="NewDialog" Value="InstallDirDlg" Condition="NOT Installed" />
                <Publish Dialog="InstallDirDlg" Control="Back" Event="NewDialog" Value="WelcomeDlg" />
        </UI>

**Comment by barnson** [comment]
Instead of `<UIRef Id="WixUI_InstallDir" />`, use `<ui:WixUI Id="WixUI_InstallDir" />`. That's required to correctly wire up the platform-specific custom actions.

**Comment by NilsHoyer** [comment]
This forces a problem with the http://wixtoolset.org/schemas/v4/wxs/ui.

**Comment by barnson** [comment]
What problem?

**Comment by chrpai** [comment]
The only "problem" I see is that if you use WiXUI_InstallDir and don't define the WIXUI_INSTALLDIR property,  it'll build and pass validation without any errors but the resulting MSI will crash with a 2819.  I'm pretty sure that's always been the behavior though.

If @NilsHoyer  is trying to author WixUI_InstallDir and bypass the EULA dialog the code should look something similiar to this.  The only difference would be whatever you named your directory table entry.  This works just fine in rc1 for me.

```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:ui="http://wixtoolset.org/schemas/v4/wxs/ui">
	<Fragment>
		<UI Id="UI">
			<ui:WixUI Id="WixUI_InstallDir" />
			<Publish Dialog="WelcomeDlg" Control="Next" Event="NewDialog" Value="InstallDirDlg" Condition="NOT Installed" Order="2" />
			<Publish Dialog="InstallDirDlg" Control="Back" Event="NewDialog" Value="WelcomeDlg" Order="2"/>
			<Property Id="WIXUI_INSTALLDIR" Value="INSTALLLOCATION"/>
		</UI>
	</Fragment>
</Wix>
```

**Comment by chrpai** [comment]
So small thing... the intellisense doesn't seem to think that ui:WiXUI should be a child of UI.  The docs website says it should and the compiler handles it just fine.

It does think it can be a child of Fragment though.

![image](https://user-images.githubusercontent.com/43178814/208560289-96b599fc-bf67-49be-a1e5-ffc18ee68918.png)

**Comment by barnson** [comment]
OK, that's a bug in the schema. It doesn't affect the build.

**Comment by NilsHoyer** [comment]
... but the LicenseAgreementDlg will be shown for me.

After accepting it (I don't like this) and I press the [Next] button, I get this error message:
> The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2819.

**Comment by NilsHoyer** [comment]
Maybe I'm too stupid. Maybe some software is too buggy, or maybe the documentation is not well.

I don't know. But I'm no longer motivated to contribute this project.

**Comment by chrpai** [comment]
@NilsHoyer I see that you said you created your first WiX project.  I'd be happy to spend an hour with you to show you an open source project that I have that builds upon WiX.  It supports WiX v3 and v4.   v3 is very stable.  v4 is very close to stable.

FWIW, this is a great time for this project because they are near the finish line and goal orriented.  Well written, actionable issues are being addressed left and right.

**Comment by NilsHoyer** [comment]
> FWIW, this is a great time for this project because they are near the finish line and goal orriented. Well written, actionable issues are being addressed left and right.

That is the reason, why I tried to contribute with my problems. I believe, reporting problems is on the same way important, like fixing bugs. But the most developer don't honor this work.

**Comment by robmen** [comment]
It is challenging to deal with issues that have multiple bugs reported in them. Better to create a separate issue for each unrelated problem. I'm going to try to enumerate the issues I see here.

* [ ] `Condition` missing from `Publish` element and extensions not allowed under `UI` element are bugs in the XSD. They need to be fixed (one was fixed already) but neither should be blocking.
* [x] `ResolvePackageDependencies` is not part of the WiX Toolset. It's part of the HeatWave design time targets. This problem is already tracked by https://github.com/firegiant/HeatWaveSupport/issues/10. It looks like they are looking for more information to reproduce the error. Perhaps you can share your project there.
* [x] Customizing WixUI is a bit different in v4. It looks like @barnson and @chrpai have been helping. I don't know that there is a bug here, so consider continuing the conversation on [Discussions](../discussions). If a bug is discovered, open that with the appropriate details.

**Comment by barnson** [comment]
`Publish/@Condition` is now in wix.xsd.

**Comment by robmen** [comment]
With the `Condition` attribute fixed, the issues here are covered. If you discover another problem, please open a new issue. If you have any more questions about the WixUI, please start with Discussions.

**Comment by chrpai** [comment]
Thanks @robmen and @barnson.   @NilsHoyer the offer to donate some of my time to you to go over all this still stands.
