### ISSUE TITLE
Cannot use harvesting in Wix v4 - NuGet package missing

### ISSUE THREAD

**Issue by BryanCrotaz** [wixtoolset/issues#7123]
See documentation at https://wixtoolset.org/docs/reference/heat/

1. Add a reference to the **Wixtoolset.Heat** NuGet package.

Nothing found in the Visual Studio 2022 NuGet Package Manager GUI.
Try it in the console:

```
nuget.exe install WixToolset.Heat
Feeds used:
  https://www.nuget.org/api/v2/
  https://nuget.pkg.github.com/silver-curve/index.json
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Installing package 'WixToolset.Heat' to 'H:\Projects\ashleigh-app-on-premise\AshleighAppOnPremise'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='WixToolset.Heat'&semVerLevel=2.0.0
  GET https://nuget.pkg.github.com/silver-curve/wixtoolset.heat/index.json
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='WixToolset.Heat'&semVerLevel=2.0.0 171ms
  NotFound https://nuget.pkg.github.com/silver-curve/wixtoolset.heat/index.json 287ms
nuget.exe : Unable to find package 'WixToolset.Heat'
At line:1 char:1
+ nuget.exe install WixToolset.Heat
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to find package 'WixToolset.Heat':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

Documentation does not say that you need to enable prerelease

**Comment by robmen** [comment]
The documentation doesn't explicitly say how to add the package reference because there are several different ways. You note two of them. Another option is to add the `PackageReference` directly. Then there is `dotnet.exe`. The latter two are explicitly called out on NuGet.org and don't require anything to enable prerelease.

I'll add a link to the NuGet.org page which has explicit instructions for those developers that are not familiar with how to use NuGet.
