### ISSUE TITLE
WiX 4 package comments

### ISSUE THREAD

**Issue by mosBrkr** [wixtoolset/issues#7369]
* Describe the scenario and benefits that the feature supports.

> In WiX 3 it was possible to set an individual comment in the package (['Package' element 'Comments' attribute](https://wixtoolset.org/docs/v3/xsd/wix/package/)) which was then added to the MSI file info.
Using WiX 4 the comment is 'hard coded'. As we are using this field for further processing (automatic deployment) the MSI it would be great to have it also in WiX 4.

* Describe how you're accomplishing the feature today (if possible).

> Setting the 'Comments' attribute in the 'Package' element (WiX 3):
`<Package Id="*" InstallerVersion="200" Comments="ExampleComment" InstallScope="perMachine" />`

* Describe what you'd like the new feature to do.

> Accept a 'Comments' attribute 🙂 
![image](https://user-images.githubusercontent.com/87169536/230310355-a857cfde-08f8-467e-854d-e8ccbadc0751.png)

I'm not sure how much my request is related to this issue: https://github.com/wixtoolset/issues/issues/5325

From my first diggings into the code and with WiX 3 as a 'template' I could try to add this enhancement so you could assign it to me.

**Comment by barnson** [comment]
We took it out because the SDK was fairly direct that it should follow a particular pattern. It can go on the `SummaryInformation` element.

**Comment by mosBrkr** [comment]
While it is relatively easy to add the parsing of the package element in the 'Compiler_Package.cs', I'm struggling with adding the 'Comments' attribute to the schema validation.

I can't figure out any location where to add it (as in WiX 3 there was the 'wix.xsd' which most probably defined the schema?). Has this anyway to do something with the WiX toolset or is it a part of 'HeatWave for VS20220' extension anyway? How could I add it there?

Also I'm not pretty sure how/where I could add tests for this little enhancement? I've seen there is a ton of TestData in the CoreIntegration test project. But to my very little experience/knowledge about this project I can't find any more or less similar tests? Could you give me a hint please?

**Comment by BMurri** [comment]
@ Core maintainers, correct me if I'm wrong, but the WiX schema files used in Visual Studio are provided by the HeatWave extension (the one that replaces v3's `wix.xsd` is now named `fg4_wix.xsd`). I'm not sure how to add to that file since it's no longer in the code repository, so you probably need to open an issue on the issues repo for that extension for the schema change(s).

Otherwise, everything you need for the solution (exclusive of tests) would go into `Compiler_Package.cs` and `Compiler_Module.cs` (probably a combination of `ParseSummaryInformationElement`, `ParsePackageElement`, and `ParseModuleElement`), and the test will be a new test where you check that the summary information comments is no longer the "hardcoded" value but is instead the value you provide in the test's `wxs` file itself. As to how to integrate that test, you're right that there doesn't seem to be a similar test to ensure that the "hardcoded" value is produced. Either way, you should test the scenario yourself and ensure that it does the right thing.

Again, @ core maintainers, maybe this doesn't require a test, especially since it's going into v5, not v4?

@barnson @robmen @rseanhall @mosBrkr

**Comment by rseanhall** [comment]
The v4 schema files are at https://github.com/wixtoolset/web/tree/master/src/xsd4. This should be testable and I would be surprised if we're not already testing something similar but I don't have time right now to look it up.

**Comment by barnson** [comment]
Schema .xsd files live at https://github.com/wixtoolset/web/tree/master/src/xsd4.

Tests are required regardless of version. https://github.com/wixtoolset/wix/blob/develop/src/wix/test/WixToolsetTest.CoreIntegration/AllUsersFixture.cs has a test that validates `_SummaryInformation` rows.

**Comment by mosBrkr** [comment]
Hi guys @barnson @robmen @rseanhall

Is there anything I could help you with resolving this request? 🙂

**Comment by SylwesterZarebski** [comment]
It is not in 4.0.4. :-(

**Comment by mosBrkr** [comment]
> It is not in 4.0.4. :-(

No but it should be contained in v5.0.0-rc.1 which is currently scheduled for tomorrow:
https://github.com/wixtoolset/issues/milestone/21

**Comment by mosBrkr** [comment]
@barnson @robmen @rseanhall
I just tried out the new RC. Unfortunately the compiler still complains about the 'Comments' attribute beeing unknown.

As far as I understood this schema check is part of the HeatWave for VS2022 extension right?
I guess there will be a new release of it as well as soon as WiX v5 is released? Is there a way to test this feature before a final release?

**Comment by mosBrkr** [comment]
> Is there anywhere documentation of migration steps from v4 to v5?

https://wixtoolset.org/docs/fivefour/
