### ISSUE TITLE
MSM Validation Still Broken in v4.0.0

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#7413]
* Which version of WiX are you building with?

4.0.0

* Which version of Visual Studio are you building with (if any)?
17.5.4

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

Heatwave 1.0.1.1

* Which version of .NET are you building with?

N/A

> (Windows version)

N/A

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

Re: issues/discussions 6524, 6567 and 6517 there are still problems with the CUBs in 4.0.0.  

Create a merge module using HeatWave and build it. Now add `<Property ID="SOMEPROP" Secure="True"/>` It will build and give these errors:
This is still broken in v4.0.0. Creating a merge module with a property that is marked Secure causes:

Severity Code Description Project File Line Suppression State
Error WIX0204 ICEM10: The property 'ProductCode' is not allowed in a Merge Module MergeModule1 C:\GitHub\EUCVA-Server\Installer\MergeModule1\wix.exe 1
Error WIX0204 ICE03: Table: Component Column: _IceM05Mark Missing specifications in _Validation Table (or Old Database) MergeModule1 C:\GitHub\EUCVA-Server\Installer\MergeModule1\obj\x64\Debug\MergeModule1.msm 1
Error WIX0204 ICE03: Table: File Column: _ICEM07CAB Missing specifications in _Validation Table (or Old Database) MergeModule1 C:\GitHub\EUCVA-Server\Installer\MergeModule1\obj\x64\Debug\MergeModule1.msm 1

However if you look at the MSM in ORCA ProductCode is no where to be found and MSM validation works.

**Comment by chrpai** [comment]
The example code to repro the issue didn't format correctly. I edited so it can be seen.

**Comment by barnson** [comment]
Any Property table row in the merge module triggers ICEM10. That's a logic error I've fixed.

The ICE03 errors are (apparently) due to temporary columns being added to the File and Component tables without matching _Validation rows. Given the lack of care shown in mergemod.cub, I'm not terribly surprised. Two options I see:

- Revert to the WiX v3.11-era mergemod.cub. It doesn't know about Arm64, so will throw ICE39 errors on Arm64 merge modules. It is otherwise correctly built but is older and is missing newer ICEs added to the current version of darice.cub.
- Explicitly code around those messages.

**Comment by chrpai** [comment]
Is this a recent fix? I don't see a PR.

**Comment by barnson** [comment]
There is no PR yet.

**Comment by barnson** [comment]
Taking option #2.
