### ISSUE TITLE
Support WIX_IS_NETFRAMEWORK_481_OR_LATER_INSTALLED

### ISSUE THREAD

**Issue by ww898** [wixtoolset/issues#7425]
.NET Framework 4.8.1 is ready for half year, but still there isn`t `WIX_IS_NETFRAMEWORK_481_OR_LATER_INSTALLED`

**Comment by robmen** [comment]
For discussion, please use the Discussions.

**Comment by robmen** [comment]
![image](https://user-images.githubusercontent.com/131904/233105518-254321ea-3bc0-400f-9f96-6be7fb9d701e.png)

**Comment by rseanhall** [comment]
@robmen I don't like how you handled this issue. There were many other options that were available to you:

1. Close the issue and request that they create a new one that follows the template.
2. Leave the issue open and request that they edit it to follow the template.
3. Convert the issue to a discussion without any comment.
4. Close the issue with the response you gave in https://github.com/orgs/wixtoolset/discussions/7426.
5. Close the issue as a duplicate and point them to discussions if they need help with using it in v4.
6. Leave the issue open, point out that it was already implemented in v4, and ask why they created the issue (maybe [doc was missing](https://github.com/wixtoolset/web/pull/198)).

All of those options would have put them on a path forward. You could have also just ignored the issue and let someone else handle it. But instead, you chose to close the issue and point them to Discussions even though you knew that this was a feature request for something that was already implemented in v4. You deliberately put them on the wrong path so that they would waste their time before you would give them the real answer. When you act in bad faith like this, you're giving the other person zero incentive to improve their behavior.

I don't want to work with anyone that intentionally wastes other people's time. I don't want to be associated with a project where the core maintainers are more interested in fighting back against their users than helping them. If you think that your behavior here is acceptable, then I'm out.

**Comment by SOHODeveloper** [comment]
> [@robmen](https://github.com/robmen) I don't like how you handled this issue. There were many other options that were available to you:
> 
> 1. Close the issue and request that they create a new one that follows the template.
> 2. Leave the issue open and request that they edit it to follow the template.
> 3. Convert the issue to a discussion without any comment.
> 4. Close the issue with the response you gave in https://github.com/orgs/wixtoolset/discussions/7426.
> 5. Close the issue as a duplicate and point them to discussions if they need help with using it in v4.
> 6. Leave the issue open, point out that it was already implemented in v4, and ask why they created the issue (maybe [doc was missing](https://github.com/wixtoolset/web/pull/198)).
> 
> All of those options would have put them on a path forward. You could have also just ignored the issue and let someone else handle it. But instead, you chose to close the issue and point them to Discussions even though you knew that this was a feature request for something that was already implemented in v4. You deliberately put them on the wrong path so that they would waste their time before you would give them the real answer. When you act in bad faith like this, you're giving the other person zero incentive to improve their behavior.
> 
> I don't want to work with anyone that intentionally wastes other people's time. I don't want to be associated with a project where the core maintainers are more interested in fighting back against their users than helping them. If you think that your behavior here is acceptable, then I'm out.

@rseanhall Thanks for calling Rob out.  I wish someone would do so every day.
