### ISSUE TITLE
WIP: WiX v5: Default root directory

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#7588]
# Default root directory

## User story

As a setup developer, if my package has no authored INSTALLFOLDER but does have a reference to INSTALLFOLDER, WiX will provide a default INSTALLFOLDER for me under `ProgramFiles6432Folder` named `[Manufacturer] [ProductName]`.

## Proposal

Packages typically have a single "root" directory -- not TARGETDIR -- where all the package's directories and files live. The HeatWave templates for a v4 package project defines such a root directory like this:

    <StandardDirectory Id="ProgramFiles6432Folder">
      <Directory
		Id="INSTALLFOLDER" 
		Name="!(bind.Property.Manufacturer) !(bind.Property.ProductName)" 
		/>
    </StandardDirectory>

What if...just hear me out...What if WiX provided that directory for you?

Like other v5 language improvements, this simplification kicks in only if no INSTALLFOLDER directory is authored and there is some kind of reference to INSTALLFOLDER. That ensures backward compatibility with WiX v4 authoring.

## Considerations

- INSTALLFOLDER is the name I chose because it's what's used in the v4 templates. I could probably be convinced another name is better, though a substantial bribe might be necessary.
- The default INSTALLFOLDER is available for both elements (e.g., `DirectoryRef`) and attributes (e.g., `ComponentGroup/@Directory`). Should it also be available as a value for `StandardDirectory`?
- Alternately, should INSTALLFOLDER be available _only_ via `StandardDirectory`?

**Comment by barnson** [comment]
Triage team: Please discuss `StandardDirectory`.

**Comment by barnson** [comment]
Consider https://github.com/wixtoolset/issues/issues/7605 stdlib concept and the idea of making more things `Overridable`.

**Comment by alejandro-merino-ng** [comment]
Hello @barnson,

I am using INSTALLDIR instead of INSTALLFOLDER in my .wxs file, and I have verified that there are no references to INSTALLFOLDER anywhere in my project. However, despite this, a default folder is still being created under C:\Program Files.

Is there an implicit behavior in WiX v5 that might be causing this, or is there a way to explicitly prevent the creation of INSTALLFOLDER when it's not referenced?

Any insights would be greatly appreciated. Thanks!
