### ISSUE TITLE
Documentation is out of sync

### ISSUE THREAD

**Issue by BryanCrotaz** [wixtoolset/issues#7810]
https://www.firegiant.com/docs/heatwave-build-tools/harvesting/ talks about using `HarvestFolder` to harvest a set of files
https://wixtoolset.org/docs/tools/heat/  talks about using `HarvestDirectory` to harvest a set of files

Guessing `HarvestFolder` is the old name for `HarvestDirectory`?

These need to be brought into sync (I think the latter is correct but as I can't make it work I'm really not sure of anything any more)!

**Comment by BryanCrotaz** [comment]
PS I've looked for the repos to submit a PR but can't find the documentation repo

**Comment by robmen** [comment]
Advanced harvesting from FireGiant has nothing to do with Heat.

**Comment by BryanCrotaz** [comment]
It's called Heat and Heatwave but they're nothing to do with each other? Heatwave is the package that you install to get Heat isn't it?

**Comment by robmen** [comment]
They have different names because they are different things. When I search for "wix heatwave" and "wix heat" I get the following two pages:

[HeatWave](https://www.firegiant.com/docs/heatwave/) - from the top of the page:  HeatWave is FireGiant's Visual Studio extension for WiX v4. HeatWave Community Edition is available free of charge...

[Heat](https://wixtoolset.org/docs/tools/heat/) - from the top of the page:  In WiX v4, Heat is available in a WiX extension NuGet Package. To use Heat to harvest directories, files, or projects...

The paid replacement @wmanning refers to is [FireGiant's Advanced Harvesting](https://www.firegiant.com/docs/heatwave-build-tools/harvesting/).
