### ISSUE TITLE
Why Filesearch is giving error

### ISSUE THREAD

**Issue by roshanpassi** [wixtoolset/issues#7950]
### WiX Version

4.0.3

### .NET or MSBuild or Visual Studio Version

.net 7

### HeatWave Version

1.0.2.1

### Windows Version

Win 10

### Repro Steps

Hii.
My task is to seach for C:\system32\drivers\wireguard.sys driver and if I found it the installation should be stopped.
VirtualBox_windows_08_01_2024_01_38_10
For this, I am doing file search and storing the result in variable "isWireguard" and then
using launch condition and giving "isWireguard" variable to condition.
But for some reason util:Filesearch is throwing error. Why is it. Can anyone help how to do it.
![VirtualBox_windows_08_01_2024_01_38_10](https://github.com/wixtoolset/issues/assets/148275677/a6dc789f-e66f-4ffe-b21c-39f04430894c)

### Actual Result

 Can anyone help how to do it.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
Your question in discussions is the right place for support questions, not issues, as the `Acknowledgements` section points out.

**Comment by robmen** [comment]
@roshanpassi, it is incredibly disrespectful of our time to fill out this form and check the box acknowledging that you were not trying to get support when your "Actual result" is a question:

> Can anyone help how to do it.

Just because you make a grammatical mistake and choose not to end that sentence with a question mark does not make it less of a question.
