### ISSUE TITLE
release URL don't reflect the version number

### ISSUE THREAD

**Issue by robUx4** [wixtoolset/issues#8097]
### WiX Version

3.14

### .NET or MSBuild or Visual Studio Version

Any

### HeatWave Version

Any

### Windows Version

Any

### Repro Repo

https://github.com/wixtoolset/wix3

### Repro Steps

Download https://github.com/wixtoolset/wix3/releases/download/wix314rtm/wix314-binaries.zip

### Actual Result

Depending on the date, the version included might be different and tarball has a mismatching. This raises some security issues of potential MITM attacks on the downloaded package. It turns out that the same URL that used to serve 3.14.0.6526 is now serving 3.14.0.8606. This is mentioned nowhere in the release page which doesn't even mention the version being provided: https://github.com/wixtoolset/wix3/releases

### Expected Result

The URL should contain the exact version which can also be linked to a proper release tag. The tarballs should **never** be changed silently.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by robmen** [comment]
The text and URL behind the link highlighted in green below are updated when the recommended build of WiX v3 changes... unless we forget. I just submitted a change to update the link to v3.14.1 (we should have done this a couple of weeks ago).

![image](https://github.com/wixtoolset/issues/assets/131904/b0113d50-04af-449e-a413-79db34268aa1)

The GitHub link you provide _could_ change since it references the release by tag (`wix314rtm`), but we control those tags in our repo, so they wouldn't change unless for a _really_ good reason, which I can't think of at this time.

Note: I don't see how WiX v3.14.0.6526 could have been available at `https://github.com/wixtoolset/wix3/releases/download/wix314rtm`. There must have been a different URL you are thinking of.

**Comment by robUx4** [comment]
I think you're right, the `3.14.0.8606` tarball may have been the only one at that URL. In our build system we use our local cache before using the remote tarball. I thought it was the other way around. So we were using `3.14.0.6526` from our cache, and we only noticed the mismatch when the local cache was failing.

However I still think the URL on GitHub should mention the hash they correspond to. You may have a simplify link elsewhere.
