### ISSUE TITLE
Error 2318:  File does not exist

### ISSUE THREAD

**Issue by EvgenPervenenko** [wixtoolset/issues#8639]
### WiX Version

5.0.1

### .NET or MSBuild or Visual Studio Version

Microsoft Visual Studio Community 2022 Version 17.8.2   ASP.NET and Web Tools   17.8.358.6298

### HeatWave Version

1.0.4.5

### Windows Version

Windows 11 Pro 21H2

### Repro Steps

When trying to remove file with path 294 symbols

example:
C:\Users\yauheni.pervenenka\AppData\Roaming\TEST_PROJECTPC\TEST_FOLDER\Thumbnails\TEST_thumb0-02-05-15d71cbff8f730aa3eb76c1debfeb761c5e37c52f2dc5ee8b0746ffe1c07d2b2_ffde29895fc0be1e_dd75f923bde3b184asdfasd fasdfasdfasdfasd fasd fasdfasdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf as.jpg

got the next error:
```
MSI (s) (FC:5C) [13:59:21:974]: Note: 1: 2318 2: C:\Users\yauheni.pervenenka\AppData\Roaming\TEST_PROJECTPC\TEST_FOLDER\Thumbnails\TEST_thumb0-02-05-15d71cbff8f730aa3eb76c1debfeb761c5e37c52f2dc5ee8b0746ffe1c07d2b2_ffde29895fc0be1e_dd75f923bde3b184asdfasd fasdfasdfasdfasd fasd fasdfasdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf as.jpg 
MSI (s) (FC:5C) [13:59:21:974]: Note: 1: 2205 2:  3: Error 
MSI (s) (FC:5C) [13:59:21:974]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 2318 
DEBUG: Error 2318:  File does not exist: C:\Users\yauheni.pervenenka\AppData\Roaming\TEST_PROJECTPC\TEST_FOLDER\Thumbnails\TEST_thumb0-02-05-15d71cbff8f730aa3eb76c1debfeb761c5e37c52f2dc5ee8b0746ffe1c07d2b2_ffde29895fc0be1e_dd75f923bde3b184asdfasd fasdfasdfasdfasd fasd fasdfasdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf as.jpg
MSI (c) (90:94) [13:59:21:974]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2318. The arguments are: C:\Users\yauheni.pervenenka\AppData\Roaming\TEST_PROJECTPC\TEST_FOLDER\Thumbnails\TEST_thumb0-02-05-15d71cbff8f730aa3eb76c1debfeb761c5e37c52f2dc5ee8b0746ffe1c07d2b2_ffde29895fc0be1e_dd75f923bde3b184asdfasd fasdfasdfasdfasd fasd fasdfasdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf as.jpg, , 
MSI (s) (FC:5C) [13:59:23:024]: Note: 1: 2205 2:  3: Error 
MSI (s) (FC:5C) [13:59:23:024]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (s) (FC:5C) [13:59:23:024]: Product: Package2 -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2318. The arguments are: C:\Users\yauheni.pervenenka\AppData\Roaming\TEST_PROJECTPC\TEST_FOLDER\Thumbnails\TEST_thumb0-02-05-15d71cbff8f730aa3eb76c1debfeb761c5e37c52f2dc5ee8b0746ffe1c07d2b2_ffde29895fc0be1e_dd75f923bde3b184asdfasd fasdfasdfasdfasd fasd fasdfasdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf as.jpg, , 

```

File exist on machine

Simple wix msi project file
```
<Project Sdk="WixToolset.Sdk/5.0.1">
  <ItemGroup>
    <PackageReference Include="WixToolset.Util.wixext" Version="5.0.1" />
  </ItemGroup>
</Project>
```

Package file:
```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:util="http://wixtoolset.org/schemas/v4/wxs/util">
  <Package Name="Package2" Manufacturer="TODO Manufacturer" Version="1.0.0.0" UpgradeCode="79e46960-5806-4c41-a821-5dc9f68ecc98">
    <MajorUpgrade DowngradeErrorMessage="!(loc.DowngradeError)" />

	<Property Id="TEMPFOLDERPATH" Secure="yes">
      <DirectorySearch Id="TempFolderSearch" Path="[AppDataFolder]TEST_PROJECTPC" />
	</Property>
	  
    <Feature Id="Main">
      <ComponentGroupRef Id="ExampleComponents" />
    </Feature>

		  <Component Id="TempFolderUn" Feature="Main" Directory="INSTALLFOLDER" Guid="*">
			  <util:RemoveFolderEx On="both" Property="TEMPFOLDERPATH" />
			  <RegistryValue Root="HKCU" Key="Software\Test\WixKeyPath" Type="string" Value=""/>
		  </Component>
	
  </Package>
</Wix>
```

### Actual Result

DEBUG: Error 2318:  File does not exist: ...
Installation/uninstallation can't be ended

### Expected Result

File removed installation/uninstallation is success

### Acknowledgements

- [x] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by bevanweiss** [comment]
I suspect it's related to the MAX_PATH limitations
https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry
It's potentially a tricky problem...

What's going to be the most beneficial is if you can create an Integration Test for the issue like https://github.com/wixtoolset/wix/tree/main/src/test/msi/TestData/TouchFileTests/TouchFile

The integration test should then have a .cs file which would setup the conditions that show the issue (i.e. a file with a long path)
https://github.com/wixtoolset/wix/tree/main/src/test/msi/WixToolsetTest.MsiE2E

If you create the integration test, then I'll see if i can fix it.

**Comment by EvgenPervenenko** [comment]
@bevanweiss hi, pls take a look
https://github.com/EvgenPervenenko/wix/commit/f8c67bd244686d4d29f5cf646fb17cfbd42fdc80

Do I have to create pr or it is enough?

**Comment by bevanweiss** [comment]
> @bevanweiss hi, done, pls take a look [EvgenPervenenko/wix@5879c57](https://github.com/EvgenPervenenko/wix/commit/5879c576b28c2881a79e489fc48d96f6baa44df9)
> 
> Do I have to create pr or it is enough?

This will suffice for me for now.  I've pulled down the commit, and have run a baseline build.  When I get home tonight I'll confirm that the test fails in the manner you've reported.
Then I'll investigate the possible fixes.

It looks like most items that side-step the MAX_PATH restriction (260 characters) also have some side effects, so the whole thing might need to be gated by a 'AllowLongPaths="Yes/[No]"' type of flag, and then possibly some data validation on the path provided (since relative paths are not supported if prefixing paths with the long path magic \\?\).

**Comment by barnson** [comment]
Windows Installer doesn't support >MAX_PATH paths.

**Comment by bevanweiss** [comment]
> Windows Installer doesn't support >MAX_PATH paths.

Yeah, this issue is only around the iterated paths from the RemoveFolderEx WiX custom action.
Adding files etc with paths > MAX_PATH would not be a thing.
However... deliberately removing a folder that contains files which have long paths 'should' work if possible.

**Comment by barnson** [comment]
The custom action doesn't support >MAX_PATH paths either, because MSI doesn't.

**Comment by bevanweiss** [comment]
@barnson is spot on.  I had failed to notice on a first look that it's actually the MSI RemoveFiles standard action that does the 'deleting' here.  I tried throwing a few different 'long path' options at it, and it wouldn't have a bar of it.

Deviating from MSI 'standard' for RemoveFiles seems fraught with risk, and opens up a pretty big support door that I can't imagine there's resourcing to support.

So the options (for you) are probably going to be:

- Ensure that you don't end up with long paths (beyond the MAX_PATH limit of 260 characters.. so 259 characters for a directory, since it needs the trailing backslash).
- Handle the deletion in your own custom action.
- Try to get Microsoft to have the RemoveFiles Standard Action appropriately deal with long paths.  You could use the Windows Feedback Hub to propose this.  It would be an issue against the Windows Installer system.  I suspect there would be limited incentive for MS to alter this... but you could give it a go.

**Comment by barnson** [comment]
It's a [semi-custom action](https://www.joyofsetup.com/2007/07/01/semi-custom-actions/) that maintains proper rollback. Custom actions that run `cmd /c rd /s/q` do not.
