### ISSUE TITLE
What's the Package/Scope default? (perMachine, perUser, perUserOrMachine)

### ISSUE THREAD

**Issue by forderud** [wixtoolset/issues#8741]
### WiX Version

5.0.1

### .NET or MSBuild or Visual Studio Version

Visual Studio 2022 LTSC 17.8

### HeatWave Version

1.0.4

### Windows Version

Win10 22H2 (x64)

### Repro Steps

Steps to reproduce:
1. Auto-upgrade a Wix3 project containing `<Package .. InstallScope="perMachine" ../>` to Wix4 from Visual Studio 2022.

![image](https://github.com/user-attachments/assets/94384969-f49f-4c90-8593-162891a39ef4)

### Actual Result

2. Observe that the `InstallScope="perMachine"` attribute is just removed. It is _not_ replaced by a `Scope="perMachine"` attribute. I'm not sure if this is a correct simplification, since the default value for the corresponding `Package/Scope` attribute in Wix4 is not documented.

### Expected Result

Could it be possible to either document the default value of the [`Package/Scope`](https://wixtoolset.org/docs/schema/wxs/package/) attribute, or update the Wix3-to-Wix4 converter to preserve the `InstallScope/Scope` attribute during the conversion?

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by bevanweiss** [comment]
The converter removes attributes that align to the default value
https://github.com/wixtoolset/wix/blob/dd2fe20d9fe58719445411524bd730495140d02f/src/wix/WixToolset.Converters/WixConverter.cs#L1433

Which is indeed the default used by the compiler
https://github.com/wixtoolset/wix/blob/dd2fe20d9fe58719445411524bd730495140d02f/src/wix/WixToolset.Core/Compiler_Package.cs#L33

there's probably quite a few more 'undocumented' defaults, I've create a PR for this one, and a couple of other adjacent attributes.
wixtoolset/web#295
If you see others, you could put together a PR to update them also :)

**Comment by forderud** [comment]
Thanks a lot @bevanweiss. Really appreciate your effort to improve the documentation here 👍

**Comment by barnson** [comment]
Manually implemented in https://github.com/wixtoolset/web/pull/298.

**Comment by bevanweiss** [comment]
> Manually implemented in [wixtoolset/web#298](https://github.com/wixtoolset/web/pull/298).

Should the WiX v3->4+ converter perhaps have the default removed (set null) for at least this item?
Currently as noted in this issue, when migrating from v3 using the converter, the scope is removed from the converted authoring if it's perMachine (the current default).
I almost think given the issues that have arisen lately due to weird authoring of mixed perMachine / perUser MSIs it would be better to require the Package/@Scope to be explicitly defined, rather than having the perMachine default.

As a step 1 in WiX v6 if the Scope attribute was missing it could be flagged as a Warning, with the message that the default perMachine is being used.  In a future version that could be an Error instead.

**Comment by robmen** [comment]
There were two mistakes in v3:
a) `perMachine` was not the default
b) the weird mix of perMachine/perUser was an easy trap to fall into

If we had got the defaults correct the first time, there'd be fewer problems with packages out there.

We fixed our mistake in v4, and v4+ is better because perUser is something a dev has to search out. This is especially good given MSIs relatively poor support for perUser packages.

PS: I haven't double-checked, but there should be a message in the conversion process that says exactly what is happening with the Scope. Devs just don't read that report.
